/**
 */

tinyMCE.addI18n('es.xoopsimagemanager_dlg',{
    tab_general:"General",
    tab_appearance:"Apariencia",
    tab_advanced:"Avanzado",
    general:"General",
    title:"Título",
    preview:"Vista Previa",
    constrain_proportions:"Restringir las proporciones",
    langdir:"Dirección de Idioma",
    langcode:"Código de Idioma",
    long_desc:"Enlace de descripción larga",
    style:"Estilo",
    classes:"Clases",
    ltr:"Izquierda a Derecha",
    rtl:"Derecha a Izquierda",
    id:"Id",
    map:"mapa de imagen",
    swap_image:"Intercambio de imagen",
    alt_image:"Imagen alternativa",
    mouseover:"para pasar el ratón sobre ",
    mouseout:"para soltar el ratón",
    misc:"Diverso",
    example_img:"Apariencia de la imagen de vista previa",
    missing_alt:"¿Está seguro de que desea continuar sin incluir una Descripción de Imágenes? Sin ella, la imagen puede no ser accesible para algunos usuarios con discapacidad, o para aquellos que utilizan un navegador de texto o navegar por la web con las imágenes desactivadas",
    dialog_title:"Administrador de imágenes",
    src:"URL de Imagen",
    alt:"Descripción de Imagen",
    list:"Lista de Imágenes",
    border:"Borde",
    dimensions:"Dimensiones",
    vspace:"Espacio Vertical",
    hspace:"Espacio Horizontal",
    align:"Alineación",
    align_baseline:"Base",
    align_top:"Arriba",
    align_middle:"Enmedio",
    align_bottom:"Abajo",
    align_texttop:"Texto arriba",
    align_textbottom:"Texto abajo",
    align_left:"Izquierda",
    align_right:"Derecha",
    image_list:"Lista de Imágenes"
});

tinyMCE.addI18n('es.xoopsimagebrowser_dlg',{
    dialog_title:"Xoops Imagebrowser",
    tab_listimages:"Imágenes",
    tab_loadimage:"Añadir imagen",
    tab_listcategories:"Categorías",
    tab_createcategory:"Añadir categoría",
    select_image: "Haga clic en una imagen para seleccionar"
});