<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


$this->holidays = array(
	'2004-1-1'=>1,'2004-1-6'=>1,'2004-4-9'=>1,'2004-4-11'=>1,
	'2004-4-12'=>1,'2004-5-1'=>1,'2004-5-20'=>1,'2004-5-30'=>1,
	'2004-5-31'=>1,'2004-6-26'=>1,'2004-11-6'=>1,'2004-12-25'=>1,
	'2004-12-26'=>1,

	'2005-1-1'=>1,'2005-1-6'=>1,'2005-3-25'=>1,'2005-3-28'=>1,
	'2005-5-1'=>1,'2005-5-5'=>1,'2005-5-16'=>1,'2005-6-25'=>1,
	'2005-11-5'=>1,'2005-12-25'=>1,'2005-12-26'=>1,
	
	'2006-1-1'=>1,'2006-1-6'=>1,'2006-4-14'=>1,'2006-4-17'=>1,
	'2006-5-1'=>1,'2006-5-25'=>1,'2006-6-5'=>1,'2006-12-25'=>1,
	'2006-12-26'=>1,

	'2007-1-1'=>1,'2007-1-6'=>1,'2007-5-1'=>1,'2007-12-25'=>1,
	'2007-12-26'=>1,
	
	);

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1:e','2:e','3:e','4:e','5:e','6:e','7:e','8:e','9:e',
	'10:e','11:e','12:e','13:e','14:e','15:e','16:e','17:e','18:e','19:e',
	'20:e','21:e','22:e','23:e','24:e','25:e','26:e','27:e','28:e','29:e',
	'30:e','31:e'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1:e','2:e','3:e','4:e','5:e','6:e','7:e','8:e','9:e',
	'10:e','11:e','12:e','13:e','14:e','15:e','16:e','17:e','18:e','19:e',
	'20:e','21:e','22:e','23:e','24:e','25:e','26:e','27:e','28:e','29:e',
	'30:e','31:e'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Vecka 0','Vecka 1','Vecka 2','Vecka 3','Vecka 4','Vecka 5','Vecka 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Sö','Må','Ti','On','To','Fr','Lö','Sö') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('S‹Ï','MéÏ','Tis','Ons','Tor','Fre','L‹Ó','S‹Ï') ;

// Can use tags (for Daily View)
$this->week_long_names = array('S‹Ïdag','MéÏdag','Tisdag','Onsdag','Torsdag','Fredag','L‹Ódag','S‹Ïdag') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Feb','Mar','Apr','Maj','Jun','Jul','Aug','Sep','Okt','Nov','Dec') ;

// Can use tags
$this->month_middle_names = array('0','Januari','Februari','Mars','April','Maj','Juni','Juli','Augusti','September','Oktober','November','December') ;

// Can use tags
$this->month_long_names = array('0','Januari','Februari','Mars','April','Maj','Juni','Juli','Augusti','September','Oktober','November','December') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'S‹Ï','MO'=>'MéÏ','TU'=>'Tis','WE'=>'Ons','TH'=>'Tor','FR'=>'Fre','SA'=>'L‹Ó') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1:a S‹Ïdagen','1MO'=>'1:a MéÏdagen','1TU'=>'1:a Tisdagen','1WE'=>'1:a Onsdagen','1TH'=>'1:a Torsdagen','1FR'=>'1:a Fredagen','1SA'=>'1:a S‹Ïdagen',
	'2SU'=>'2:a S‹Ïdagen','2MO'=>'2:a MéÏdagen','2TU'=>'2:a Tisdagen','2WE'=>'2:a Onsdagen','2TH'=>'2:a Torsdagen','2FR'=>'2:a Fredagen','2SA'=>'2:a S‹Ïdagen',
	'3SU'=>'3:e S‹Ïdagen','3MO'=>'3:e MéÏdagen','3TU'=>'3:e Tisdagen','3WE'=>'3:e Onsdagen','3TH'=>'3:e Torsdagen','3FR'=>'3:e Fredagen','3SA'=>'3:a S‹Ïdagen',
	'4SU'=>'4:e S‹Ïdagen','4MO'=>'4:e MéÏdagen','4TU'=>'4:e Tisdagen','4WE'=>'4:e Onsdagen','4TH'=>'4:e Torsdagen','4FR'=>'4:e Fredagen','4SA'=>'4:a S‹Ïdagen',
	'-1SU'=>'Sista S‹Ïdagen','-1MO'=>'Sista MéÏdagen','-1TU'=>'Sista Tisdagen','-1WE'=>'Sista Onsdagen','-1TH'=>'Sista Torsdagen','-1FR'=>'Sista Fredagen','-1SA'=>'Sista S‹Ïdagen'
	) ;



?>
