<?php
// $Id: apcal_vars.phtml, v 0.5 2003/11/07 20:00:09$
//%%%%%%	Admin Module Name  APCal 	%%%%%

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


$this->holidays = array(
	'2003-1-1'=>1,'2003-1-20'=>1,'2003-2-12'=>1,'2003-2-17'=>1,
	'2003-3-17'=>1,'2003-5-26'=>1,'2003-7-4'=>1,'2003-9-1'=>1,
	'2003-10-13'=>1,'2003-11-11'=>1,'2003-11-27'=>1,'2003-12-24'=>1,

	'2004-1-1'=>1,'2004-1-19'=>1,'2004-2-12'=>1,'2004-2-16'=>1,
	'2004-3-17'=>1,'2004-5-31'=>1,'2004-7-4'=>1,'2004-9-6'=>1,
	'2004-10-11'=>1,'2004-11-11'=>1,'2004-11-25'=>1,'2004-12-24'=>1,
	);


// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Semana 0','Semana 1','Semana 2','Semana 3','Semana 4','Semana 5','Semana 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Do','Lu','Ma','Mi','Ju','Vi','Sa','Do') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Dom','Lun','Mar','Mie','Jue','Vie','Sab','Dom') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Domingo','Lunes','Martes','Mi&eacute;rcoles','Jueves','Viernes','S&aacute;bado','Domingo') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic') ;

// Can use tags
$this->month_middle_names = array('0','Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic') ;

// Can use tags
$this->month_long_names = array('0','Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Dom','MO'=>'Lun','TU'=>'Mar','WE'=>'Mie','TH'=>'Jue','FR'=>'Vie','SA'=>'Sab') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'Primer Domingo','1MO'=>'Primer Lunes','1TU'=>'Primer Martes','1WE'=>'Primer Mi&eacute;rcoles','1TH'=>'Primer Jueves','1FR'=>'Primer Viernes','1SA'=>'Primer S&aacute;bado',
	'2SU'=>'Segundo Domingo','2MO'=>'Segundo Lunes','2TU'=>'Segundo Martes','2WE'=>'Segundo Mi&eacute;rcoles','2TH'=>'Segundo Jueves','2FR'=>'Segundo Viernes','2SA'=>'Segundo S&aacute;bado',
	'3SU'=>'Tercer Domingo','3MO'=>'Tercer Lunes','3TU'=>'Tercer Martes','3WE'=>'Tercer Mi&eacute;rcoles','3TH'=>'Tercer Jueves','3FR'=>'Tercer Viernes','3SA'=>'Tercer S&aacute;bado',
	'4SU'=>'Cuarto Domingo','4MO'=>'Cuarto Lunes','4TU'=>'Cuarto Martes','4WE'=>'Cuarto Mi&eacute;rcoles','Cuarto'=>'Cuarto Jueves','4FR'=>'Cuarto Viernes','4SA'=>'Cuarto S&aacute;bado',
	'-1SU'=>'Domingo pasado','-1MO'=>'Lunes pasado','-1TU'=>'Martes pasado','-1WE'=>'Mi&eacute;rcoles pasado','-1TH'=>'Jueves pasado','-1FR'=>'Viernes pasado','-1SA'=>'S&aacute;bado pasado'
	) ;



?>
