<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


$this->holidays = array(
	'2004-12-25'=>1,

	'2005-1-1'=>1,'2005-1-6'=>1,'2005-3-28'=>1,'2005-4-25'=>1,
	'2005-6-2'=>1,'2005-8-15'=>1,'2005-11-1'=>1,'2005-12-8'=>1,
	'2005-12-26'=>1
	);

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Sett.0','Sett.1','Sett.2','Sett.3','Sett.4','Sett.5','Sett.6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Do','Lu','Ma','Me','Gi','Ve','Sa','Do') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Dom','Lun','Mar','Mer','Gio','Ven','Sab','Dom') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Domenica','Luned&igrave;','Marted&igrave;','Mercoled&igrave;','Gioved&igrave;','Venerd&igrave;','Sabato','Domenica') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic') ;

// Can use tags
$this->month_middle_names = array('0','Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic') ;

// Can use tags
$this->month_long_names = array('0','Gennaio','Febbraio','Marzo','Aprile','Maggio','Giugno','Luglio','Agosto','Settembre','Ottobre','Novembre','Dicembre') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Dom','MO'=>'Lun','TU'=>'Mar','WE'=>'Mer','TH'=>'Gio','FR'=>'Ven','SA'=>'Sab') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1&ordf; Domenica','1MO'=>'1&deg; Luned&igrave;','1TU'=>'1&deg; Marted&igrave;','1WE'=>'1&deg; Mercoled&igrave;','1TH'=>'1&deg; Gioved&igrave;','1FR'=>'1&deg; Venerd&igrave;','1SA'=>'1&deg; Sabato',
	'2SU'=>'2&ordf; Domenica','2MO'=>'2&deg; Luned&igrave;','2TU'=>'2&deg; Marted&igrave;','2WE'=>'2&deg; Mercoled&igrave;','2TH'=>'2&deg; Gioved&igrave;','2FR'=>'2&deg; Venerd&igrave;','2SA'=>'2&deg; Sabato',
	'3SU'=>'3&ordf; Domenica','3MO'=>'3&deg; Luned&igrave;','3TU'=>'3&deg; Marted&igrave;','3WE'=>'3&deg; Mercoled&igrave;','3TH'=>'3&deg; Gioved&igrave;','3FR'=>'3&deg; Venerd&igrave;','3SA'=>'3&deg; Sabato',
	'4SU'=>'4&ordf; Domenica','4MO'=>'4&deg; Luned&igrave;','4TU'=>'4&deg; Marted&igrave;','4WE'=>'4&deg; Mercoled&igrave;','4TH'=>'4&deg; Gioved&igrave;','4FR'=>'4&deg; Venerd&igrave;','4SA'=>'4&deg; Sabato',
	'-1SU'=>'Ultima Domenica','-1MO'=>'Ultimo Luned&igrave;','-1TU'=>'Ultimo Marted&igrave;','-1WE'=>'Ultimo Mercoled&igrave;','-1TH'=>'Ultimo Gioved&igrave;','-1FR'=>'Ultimo Venerd&igrave;','-1SA'=>'Ultimo Sabato'
	) ;



?>
