<?php //* Brazilian Portuguese Translation by Marcelo Yuji Himoro <www.yuji.eu.org> *//

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


$this->holidays = array(
	'2001-2-26'=>1,'2001-2-27'=>1,'2001-4-13'=>1,'2001-6-14'=>1,
	'2002-2-11'=>1,'2002-2-12'=>1,'2002-3-29'=>1,'2002-5-30'=>1,
	'2003-3-3'=>1,'2003-3-4'=>1,'2003-4-18'=>1,'2003-6-19'=>1,
	'2004-2-23'=>1,'2004-2-24'=>1,'2004-4-9'=>1,'2004-6-10'=>1,
	'2005-2-7'=>1,'2005-2-8'=>1,'2005-3-25'=>1,'2005-5-26'=>1,
	'2006-2-27'=>1,'2006-2-28'=>1,'2006-4-14'=>1,'2006-6-15'=>1,
	'2007-2-19'=>1,'2007-2-20'=>1,'2007-4-6'=>1,'2007-6-7'=>1,
	'2008-2-4'=>1,'2008-2-5'=>1,'2008-3-21'=>1,'2008-5-22'=>1,
	'2009-2-23'=>1,'2009-2-24'=>1,'2009-4-10'=>1,'2009-6-11'=>1,
	'2010-2-15'=>1,'2010-2-16'=>1,'2010-4-2'=>1,'2010-6-3'=>1,
	);
	
for( $y = 2001 ; $y <= 2010 ; $y ++ ) {
	$this->holidays[ "{$y}-1-1" ] = 1 ;
	$this->holidays[ "{$y}-4-21" ] = 1 ;
	$this->holidays[ "{$y}-5-1" ] = 1 ;
	$this->holidays[ "{$y}-9-7" ] = 1 ;
	$this->holidays[ "{$y}-10-12" ] = 1 ;
	$this->holidays[ "{$y}-11-2" ] = 1 ;
	$this->holidays[ "{$y}-11-15" ] = 1 ;
	$this->holidays[ "{$y}-12-25" ] = 1 ;
}

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Semana 0','Semana 1','Semana 2','Semana 3','Semana 4','Semana 5','Semana 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('D','S','T','Q','Q','S','S','D') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('DOM','SEG','TER','QUA','QUI','SEX','SAB','DOM') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Domingo','Segunda','TeríÂ','Quarta','Quinta','Sexta','Sabado','Domingo') ;

// Can't use tags (for options)
$this->month_short_names = array('0','1','2','3','4','5','6','7','8','9','10','11','12') ;

// Can use tags
$this->month_middle_names = array('0','JAN','FEV','MAR','ABR','MAI','JUN','JUL','AGO','SET','OUT','NOV','DEZ') ;

// Can use tags
$this->month_long_names = array('0','Janeiro','Fevereiro','MaríÐ','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'DOM','MO'=>'SEG','TU'=>'TER','WE'=>'QUA','TH'=>'QUI','FR'=>'SEX','SA'=>'SAB') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1Žº Domingo','1MO'=>'1Žª Segunda','1TU'=>'1Žª TeríÂ','1WE'=>'1Žª Quarta','1TH'=>'1Žª Quinta','1FR'=>'1Žª Sexta','1SA'=>'1Žº SáÃado',
	'2SU'=>'2Žº Domingo','2MO'=>'2Žª Segunda','2TU'=>'2Žª TeríÂ','2WE'=>'2Žª Quarta','2TH'=>'2Žª Quinta','2FR'=>'2Žª Sexta','2SA'=>'2Žº SáÃado',
	'3SU'=>'3Žº Domingo','3MO'=>'3Žª Segunda','3TU'=>'3Žª TeríÂ','3WE'=>'3Žª Quarta','3TH'=>'3Žª Quinta','3FR'=>'3Žª Sexta','3SA'=>'3Žº SáÃado',
	'4SU'=>'4Žº Domingo','4MO'=>'4Žª Segunda','4TU'=>'4Žª TeríÂ','4WE'=>'4Žª Quarta','4TH'=>'4Žª Quinta','4FR'=>'4Žª Sexta','4SA'=>'4Žº SáÃado',
	'-1SU'=>'Domingo passado','-1MO'=>'Segunda passada','-1TU'=>'TeríÂ passada','-1WE'=>'Quarta passada','-1TH'=>'Quinta passada','-1FR'=>'Sexta passada','-1SA'=>'SáÃado passado'
	) ;



?>
