<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;

$this->holidays = array(
	'2004-1-1'=>1,'2004-4-12'=>1,'2004-5-1'=>1,'2004-5-8'=>1,
	'2004-5-20'=>1,'2004-5-31'=>1,'2004-7-14'=>1,'2004-8-15'=>1,'2004-11-1'=>1,
	'2004-11-11'=>1,'2004-12-25'=>1,

	'2005-1-1'=>1,'2005-3-27'=>1,'2004-5-1'=>1,'2004-5-5'=>1,
	'2004-5-8'=>1,'2004-5-16'=>1,'2004-7-14'=>1,'2004-8-15'=>1,'2004-11-1'=>1,
	'2004-11-11'=>1,'2004-12-25'=>1,

	);

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Semaine 0','Semaine 1','Semaine 2','Semaine 3','Semaine 4','Semaine 5','Semaine 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Di','Lu','Ma','Me','Je','Ve','Sa','Di') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Dim','Lun','Mar','Mer','Jeu','Ven','Sam','Dim') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Fev','Mar','Avr','Mai','Jui','Juil','Aou','Sep','Oct','Nov','Dec') ;

// Can use tags
$this->month_middle_names = array('0','Jan','Fev','Mar','Avr','Mai','Jui','Juil','Aou','Sep','Oct','Nov','Dec') ;

// Can use tags
$this->month_long_names = array('0','Janvier','F&eacute;vrier','Mars','Avril','Mai','Juin','Juillet','Ao&ucirc;t','Septembre','Octobre','Novembre','D&eacute;cembre') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Dim','MO'=>'Lun','TU'=>'Mar','WE'=>'Mer','TH'=>'Jeu','FR'=>'Ven','SA'=>'Sam') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1er Dimanche','1MO'=>'1er Lundi','1TU'=>'1er Mardi','1WE'=>'1er Mercredi','1TH'=>'1er Jeudi','1FR'=>'1er Vendredi','1SA'=>'1er Samedi',
	'2SU'=>'2&egrave;me Dimanche','2MO'=>'2&egrave;me Lundi','2TU'=>'2&egrave;me Mardi','2WE'=>'2&egrave;me Mercredi','2TH'=>'2&egrave;me Jeudi','2FR'=>'2&egrave;me Vendredi','2SA'=>'2&egrave;me Samedi',
	'3SU'=>'3&egrave;me Dimanche','3MO'=>'3&egrave;me Lundi','3TU'=>'3&egrave;me Mardi','3WE'=>'3&egrave;me Mercredi','3TH'=>'3&egrave;me Jeudi','3FR'=>'3&egrave;me Vendredi','3SA'=>'3&egrave;me Samedi',
	'4SU'=>'4&egrave;me Dimanche','4MO'=>'4&egrave;me Lundi','4TU'=>'4&egrave;me Mardi','4WE'=>'4&egrave;me Mercredi','4TH'=>'4&egrave;me Jeudi','4FR'=>'4&egrave;me Vendredi','4SA'=>'4&egrave;me Samedi',
	'-1SU'=>'Dimanche pr&eacute;c&eacute;dent','-1MO'=>'Lundi pr&eacute;c&eacute;dent','-1TU'=>'Mardi pr&eacute;c&eacute;dent','-1WE'=>'Mercredi pr&eacute;c&eacute;dent','-1TH'=>'Jeudi pr&eacute;c&eacute;dent','-1FR'=>'Vendredi pr&eacute;c&eacute;dent','-1SA'=>'Samedi pr&eacute;c&eacute;dent'
	) ;



?>