<?php
/**
* XOOPS - PHP Content Management System
* Copyright (c) 2001 - 2006 <http://www.xoops.org/>
*
* Module: multiMenu 1.90
* Licence : GPL
* Authors :
*           - solo (http://www.wolfpackclan.com/wolfactory)
*			- herve (http://www.herve-thouzard.com)
*			- blueteen (http://myxoops.romanais.info)
*			- DuGris (http://www.dugris.info)
*/

 $main_val_array['introduction']  =  array( ''      => 'Ce module permet de gnrer des listes de lien ou menus manuellement ou automatiquement.

Voici les variables de template disponibles pour vos templates personnalises.

2 types de variables : <ul>
<li><b>les variables fixes</b>
<i>Ces variables sont pour la plupart dfinies par dfaut, ou dans les prfrences du module.</i>
</li>
<li><b>les variables dynamiques </b>
<i>Ces variables sont dfinies en fonction du contenu de chaque menu, ou des pages cres par l\'utilisateur. 
Elles sont valables aussi bien pour les pages de contenu du module que des blocs.</i></li>
</ul>' );

 $main_val_array['language_define'] =  array(
                                  '<{$index}>'        => 'صفحه اصلی',
                                  '<{$other}>'        => 'دیگر',
                                  '<{$sourcecode}>'   => 'کد منبع '
                                   );


 $main_val_array['fixes_item'] =  array(
                                  '<{$id}>'            => '[MENU] ID منو.|1',
                                  '<{$menu}>'          => '[MENU] ID منو.|1',
                                  '<{$css_link}>'      => '[MENU] URL of the current menu .CSS file (if any).|http:&#47;&#47;[..]/multimenu_my_menu.css',
                                  '<{$script_link}>'   => '[MENU] URL of the current menu .JS file (if any)..|http:&#47;&#47;[..]/multimenu_my_menu.js',
                                  '<{$status}>'        => '[MENU] Current menu status (0 : Offline, 1 : Online, 2 : Hidden).|1',
                                  '<{$title}>'         => '[MENU] Current menu title.|User menu',
                                  '<{$css}>'           => '[MENU] Current menu style sheet definitions.|multimenu_1 {color:Red;}',
                                  '<{$description}>'   => '[MENU] Current menu description text.|Here is the user menu.',

                                  '<{$banner_url}>'    => '[PREF] URL of the modules\' banner.|http:&#47;&#47;[..]/banner.gif',
                                  '<{$background}>'    => '[PREF] URL of the modules\' background picture.|http:&#47;&#47;[..]/background_image.gif',
                                  '<{$image_width}>'   => '[PREF] Default picture width.|160',
                                  '<{$image_height}>'  => '[PREF] Default picture height.|160',
                                  '<{$edit_mode}>'     => '[PREF] Activate the "Editing" mode (display current menu source code at page bottom).|1',
                                  '<{$cols}>'          => '[PREF] Number of columns.|3',
                                  '<{$duration}>'      => '[PREF] Duration of an animation in milliseconds.|1000',
                                  '<{$transition}>'    => '[PREF] Transition of an animation in milliseconds.|1000',
                                  '<{$item_list}>'     => '[PREF] Display available menus.|1',
                                  '<{$item}>'          => '[PREF] Default item names used in pages.|Menus',
                                  '<{$item_display_selectmode}>'   => '[PREF] Display mode of all available templates.|select.html',

                                  '<{$ii}>'            => 'Total links in the current menu.|10',
                                  '<{$i}>'             => 'Total links per column (rounded number).|5',
                                  '<{$i_main}>'        => 'Total mainlinks (without any sublinks) per columns (rounded number).|3',
                                  '<{$mode}>'          => 'Current page\'s template (or set by default in module settings).|include/multimenu_ul.html',
                                  '<{$module}>'        => 'Module\'s directory (ie : multimenu)|multimenu',
                                  '<{$banner}>'        => 'Module\'s banner Html code.|&lt;img src="http:&#47;&#47;[..]/banner.gif" /&gt;',
                                  '<{$admin}>'         => 'Module admin links.|',
                                  '<{$data_list}>'     => 'Data\'s list generated by the current menu. Find list variables below.|Array'
                                   );


 $main_val_array['variables_item'] =  array(
                                  '<{item.id}>'          => 'Link ID.|2',
                                  '<{$item.pid}>'        => 'Parent link ID (main link).|1',
                                  '<{$item.catid}>'      => 'Current menu ID.|1',
                                  '<{$item.type}>'       => 'Link type (permanent or relative).|permanent',
                                  '<{$item.status}>'     => 'Link status (0 : offline or 1 : onligne).|1',
                                  '<{$item.weight}>'     => 'Link weight.|100',

                                  '<{$item.title}>'      => 'Link title.|Home',
                                  '<{$item.title|addslashes}>'=>'Protected link title (for javascript codes).|Home\\\'s',
                                  '<{$item.alt_title}>'  => 'Alternative balise (or tooltip).|This website home page',
                                  
                                  '<{$item.image}>'     => 'Default image url. Distant image is priore to hosted picture.|http:&#47;&#47;[..]/image.gif',
                                  '<{$item.image_a}>'   => 'Distant image\'s url.|http:&#47;&#47;[..]/image.gif',
                                  '<{$item.image_b}>'   => 'Hosted image\'s url.|http:&#47;&#47;[..]/image_b.gif',

                                  '<{$item.query}>'      => 'Current link query (if any).|news',
                                  '<{$item.target}>'     => 'Link\'s target (target="_blank" or popgen code if link point to a picture).|_blank',
                                  '<{$item.css}>'        => 'CSS definitions (no class, nore ID).|color:Red;',
                                  '<{$item.link_status}>'=> 'Link type (top, link or sublink).|link',
                                  '<{$item.num}>'        => 'Link order number.|1',
                                  '<{$item.num_main}>'   => 'Main link order number.|1'
                                 );

$main_val_array['author word'] =  array( ''      => 'برای فعال کردن تمپلیت دست ساز خود :
 1. تمپلیت دست ساز خود را به شاخه "templates/include/" منتقل کنید ;
 2. ماژول را به روز کنید ;
 3. تمپلیت دست ساز خود را در تنظیمات ماژول فعال کنید.' );

?>