/**
* Translation of TinyMCE for Persian users
*
* @copyright	      http://www.impresscms.org/ The ImpressCMS Project 
* @license		http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU General Public License (GPL)
* @package	      Translations
* @since		 3.0.6.2
* @author		Sina Asghari <pesian_stranger@users.sourceforge.net>
* @version		$Id$
*/
tinyMCE.addI18n('fa.table_dlg',{
general_tab:"عمومی",
advanced_tab:"پیشرفته",
general_props:"مشخصات عمومی",
advanced_props:"مشخصات پیشرفته",
rowtype:"سطر در بخش جدول",
title:"درج/ویرایش جدول",
width:"پهنا",
height:"ارتفاع",
cols:"ستون‌ها",
rows:"سطرها",
cellspacing:"فاصله خانه",
cellpadding:"فاصله بین خانه‌ها",
border:"حاشیه",
align:"هم‌ترازی",
align_default:"پیشفرض",
align_left:"چپ",
align_right:"راست",
align_middle:"وسط",
row_title:"مشخصات سطر جدول",
cell_title:"مشخصات خانه جدول",
cell_type:"نوع خانه",
valign:"تراز عمودی",
align_top:"بالا",
align_bottom:"پایین",
bordercolor:"رنگ حاشیه",
bgcolor:"رنگ پس‌زمینه",
merge_cells_title:"ادغام خانه‌های جدول",
id:"شناسه",
style: "ترکیب‌بندی",
langdir:"جهت زبان",
langcode:"کد زبان",
mime:"نوع پسوند هدف",
ltr:"چپ به راست",
rtl:"راست به چپ",
bgimage:"تصویر پس‌زمینه",
summary:"خلاصه",
td:"داده",
th:"سر",
cell_cell:"به‌روز رسانی خانه فعلی",
cell_row:"به‌روز رسانی تمام خانه‌های در سطر",
cell_all:"به‌روز رسانی تمام خانه‌های در جدول",
row_row:"به‌روز رسانی سطر فعلی",
row_odd:"به‌روز رسانی سطرهای فرد در جدول",
row_even:"به‌روز رسانی سطرهای زوج در جدول",
row_all:"به‌روز رسانی تمام سطرها در جدول",
thead:"سر جدول",
tbody:"بدنه جدول",
tfoot:"پایین جدول",
scope:"محدوده",
rowgroup:"گروه سطر",
colgroup:"گروه ستون",
col_limit:"شما از حداکثر تعداد {$cols} ستون تجاوز کردید.",
row_limit:"شما از حداکثر تعداد {$rows} سطر تجاوز کردید.",
cell_limit:"شما از حداکثر تعداد {$cells} خانه تجاوز کردید.",
missing_scope: "آیا شما از ادامه دادن بدون تعیین یک محدوده برای خانه سر این جدول اطمینان دارید . بدون آن ، ممکن است برای برخی کاربران ، درک محتوای داده‌های نمایش داده شده جدول مشکل باشد.",
caption:"Table caption",
frame:"Frame",
frame_none:"هیچ کدام",
frame_groups:"گروه‌ها",
frame_rows:"سطرها",
frame_cols:"ستون‌ها",
frame_all:"همه",
rules:"قوانین",
rules_void:"void",
rules_above:"بالا",
rules_below:"پاین",
rules_hsides:"گوشه‌های افقی",
rules_lhs:"hs چپ",
rules_rhs:"hs راست",
rules_vsides:"گوشه‌های عمودی",
rules_box:"جعبه",
rules_border:"محدوده",
});