<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


$this->holidays = array(
	'2003-1-1'=>1,'2003-1-20'=>1,'2003-2-12'=>1,'2003-2-17'=>1,
	'2003-3-17'=>1,'2003-5-26'=>1,'2003-7-4'=>1,'2003-9-1'=>1,
	'2003-10-13'=>1,'2003-11-11'=>1,'2003-11-27'=>1,'2003-12-24'=>1,

	'2004-1-1'=>1,'2004-1-19'=>1,'2004-2-12'=>1,'2004-2-16'=>1,
	'2004-3-17'=>1,'2004-5-31'=>1,'2004-7-4'=>1,'2004-9-6'=>1,
	'2004-10-11'=>1,'2004-11-11'=>1,'2004-11-25'=>1,'2004-12-24'=>1,

	);

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Semana 0','Semana 1','Semana 2','Semana 3','Semana 4','Semana 5','Semana 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Do','Se','Te','Qu','Qu','Se','Sa','Do') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Dom','Seg','Ter','Qua','Qui','Sex','Sab','Dom') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Domingo','Segunda','TeríÂ','Quarta','Quinta','Sexta','SáÃado','Domingo') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez') ;

// Can use tags
$this->month_middle_names = array('0','Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez') ;

// Can use tags
$this->month_long_names = array('0','Janeiro','Fevereiro','MaríÐ','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Dom','MO'=>'Seg','TU'=>'Ter','WE'=>'Qua','TH'=>'Qui','FR'=>'Sex','SA'=>'Sab') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1o Domingo','1MO'=>'1a Segunda','1TU'=>'1a TeríÂ','1WE'=>'1a Quarta','1TH'=>'1a Quinta','1FR'=>'1a Sexta','1SA'=>'1o SáÃado',
	'2SU'=>'2o Domingo','2MO'=>'2a Segunda','2TU'=>'2a TeríÂ','2WE'=>'2a Quarta','2TH'=>'2a Quinta','2FR'=>'2a Sexta','2SA'=>'2o SáÃado',
	'3SU'=>'3o Domingo','3MO'=>'3a Segunda','3TU'=>'3a TeríÂ','3WE'=>'3a Quarta','3TH'=>'3a Quinta','3FR'=>'3a Sexta','3SA'=>'3o SáÃado',
	'4SU'=>'4o Domingo','4MO'=>'4a Segunda','4TU'=>'4a TeríÂ','4WE'=>'4a Quarta','4TH'=>'4a Quinta','4FR'=>'4a Sexta','4SA'=>'4o SáÃado',
	'-1SU'=>'Domingo anterior','-1MO'=>'Segunda anterior','-1TU'=>'TeríÂ anterior','-1WE'=>'Quarta anterior','-1TH'=>'Quinta anterior','-1FR'=>'Sexta anterior','-1SA'=>'SáÃado anterior'
	) ;



?>
