<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;

// Can't use tags (for options)
$this->date_short_names = array(
	'0日','1日','2日','3日','4日','5日','6日','7日','8日','9日',
	'10日','11日','12日','13日','14日','15日','16日','17日','18日','19日',
	'20日','21日','22日','23日','24日','25日','26日','27日','28日','29日',
	'30日','31日'
	) ;

// Can use tags
$this->date_long_names = array(
	'0日','1日','2日','3日','4日','5日','6日','7日','8日','9日',
	'10日','11日','12日','13日','14日','15日','16日','17日','18日','19日',
	'20日','21日','22日','23日','24日','25日','26日','27日','28日','29日',
	'30日','31日'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('第0週','第1週','第2週','第3週','第4週','第5週','第6週') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('日','一','二','三','四','五','六','日') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('星期日','星期一','星期二','星期三','星期四','星期五','星期六','星期日') ;

// Can use tags (for Daily View)
$this->week_long_names = array('星期日','星期一','星期二','星期三','星期四','星期五','星期六','星期日') ;

// Can't use tags (for options)
$this->month_short_names = array('0','1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月') ;

// Can use tags
$this->month_middle_names = array('0','1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月') ;

// Can use tags
$this->month_long_names = array('0','1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'星期日','MO'=>'星期一','TU'=>'星期二','WE'=>'星期三','TH'=>'星期四','FR'=>'星期五','SA'=>'星期六') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'第一個星期日','1MO'=>'第一個星期一','1TU'=>'第一個星期二','1WE'=>'第一個星期三','1TH'=>'第一個星期四','1FR'=>'第一個星期五','1SA'=>'第一個星期六',
	'2SU'=>'第二個星期日','2MO'=>'第二個星期一','2TU'=>'第二個星期二','2WE'=>'第二個星期三','2TH'=>'第二個星期四','2FR'=>'第二個星期五','2SA'=>'第二個星期六',
	'3SU'=>'第三個星期日','3MO'=>'第三個星期一','3TU'=>'第三個星期二','3WE'=>'第三個星期三','3TH'=>'第三個星期四','3FR'=>'第三個星期五','3SA'=>'第三個星期六',
	'4SU'=>'第四個星期日','4MO'=>'第四個星期一','4TU'=>'第四個星期二','4WE'=>'第四個星期三','4TH'=>'第四個星期四','4FR'=>'第四個星期五','4SA'=>'第四個星期六',
	'-1SU'=>'最後一個星期日','-1MO'=>'最後一個星期一','-1TU'=>'最後一個星期二','-1WE'=>'最後一個星期三','-1TH'=>'最後一個星期四','-1FR'=>'最後一個星期五','-1SA'=>'最後一個星期六'
	) ;



?>
