<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'00','01','02','03','04','05',
	'06','07','08','09','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 00','next 01','next 02','next 03','next 04','next 05',
	'next 06','next 07','next 08','next 09','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 00','AM 01','AM 02','AM 03','AM 04','AM 05',
	'AM 06','AM 07','AM 08','AM 09','AM 10','AM 11',
	'PM 00','PM 01','PM 02','PM 03','PM 04','PM 05',
	'PM 06','PM 07','PM 08','PM 09','PM 10','PM 11',
	'next AM 00','next AM 01','next AM 02','next AM 03','next AM 04','next AM 05',
	'next AM 06','next AM 07','next AM 08','next AM 09','next AM 10','next AM 11'
	) ;

// Austrian holidays
/* $this->holidays = array(
	'2003-1-1'=>1,'2003-1-6'=>1,'2003-4-21'=>1,'2003-5-1'=>1,
	'2003-5-29'=>1,'2003-6-9'=>1,'2003-6-19'=>1, '2003-8-15'=>1,
	'2003-10-26'=>1,'2003-11-1'=>1,'2003-12-8'=>1,'2003-12-25'=>1,
	'2003-12-26'=>1,

	'2004-1-1'=>1,'2004-1-6'=>1,'2004-4-12'=>1,'2004-5-1'=>1,
	'2004-5-20'=>1,'2004-5-31'=>1,'2004-6-10'=>1,'2004-8-15'=>1,
	'2004-10-26'=>1,'2004-11-1'=>1,'2004-12-8'=>1,'2004-12-25'=>1,
	'2004-12-25'=>1,

	); */

// Can't use tags (for options)
$this->date_short_names = array(
	'00.','01.','02.','03.','04.','05.','06.','07.','08.','09.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can use tags
$this->date_long_names = array(
	'00.','01.','02.','03.','04.','05.','06.','07.','08.','09.',
	'10.','11.','12.','13.','14.','15.','16.','17.','18.','19.',
	'20.','21.','22.','23.','24.','25.','26.','27.','28.','29.',
	'30.','31.'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Woche 0','Woche 1','Woche 2','Woche 3','Woche 4','Woche 5','Woche 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('So','Mo','Di','Mi','Do','Fr','Sa','So') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('So','Mo','Di','Mi','Do','Fr','Sa','So') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Germany
//$this->month_short_names = array('0','Jän','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Austria

// Can use tags
$this->month_middle_names = array('0','Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Germany
//$this->month_middle_names = array('0','Jän','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez') ; // Austria

// Can use tags
$this->month_long_names = array('0','Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember') ; // Germany
//$this->month_long_names = array('0','Jänner','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember') ; // Austria

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'So','MO'=>'Mo','TU'=>'Di','WE'=>'Mi','TH'=>'Do','FR'=>'Fr','SA'=>'Sa') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1. Sonntag','1MO'=>'1. Montag','1TU'=>'1. Dienstag','1WE'=>'1. Mittwoch','1TH'=>'1. Donnerstag','1FR'=>'1. Freitag','1SA'=>'1. Samstag',
	'2SU'=>'2. Sonntag','2MO'=>'2. Montag','2TU'=>'2. Dienstag','2WE'=>'2. Mittwoch','2TH'=>'2. Donnerstag','2FR'=>'2. Freitag','2SA'=>'2. Samstag',
	'3SU'=>'3. Sonntag','3MO'=>'3. Montag','3TU'=>'3. Dienstag','3WE'=>'3. Mittwoch','3TH'=>'3. Donnerstag','3FR'=>'3. Freitag','3SA'=>'3. Samstag',
	'4SU'=>'4. Sonntag','4MO'=>'4. Montag','4TU'=>'4. Dienstag','4WE'=>'4. Mittwoch','4TH'=>'4. Donnerstag','4FR'=>'4. Freitag','4SA'=>'4. Samstag',
	'-1SU'=>'Letzter Sonntag','-1MO'=>'Letzter Montag','-1TU'=>'Letzter Dienstag','-1WE'=>'Letzter Mittwoch','-1TH'=>'Letzter Donnerstag','-1FR'=>'Letzter Freitag','-1SA'=>'Letzter Samstag'
	) ;

?>
