<?php

/**
* $Id: admin.php 1304 2010-10-17 22:21:07Z kris_fr $
* Module: SmartFAQ
* Author: The SmartFactory <www.smartfactory.ca>
* Licence: GNU
*/

define('_AM_SF_ABOUT', 'A propos');
define('_AM_SF_ACTION', 'Action');
define('_AM_SF_ADMINCOLMNGMT', 'Gestion des Cat&#233;gories');
define('_AM_SF_ADMIN_CATS', 'Choisissez les Cat&#233;gories que chaque groupe peut mod&#233;rer');
define('_AM_SF_ALL', 'Tout');
define('_AM_SF_ALL_EXP', '<strong>Tous les status</strong> : Toutes les questions et r&#233;ponses de ce module, quel que soit leur statut.');
define('_AM_SF_ALLOWCOMMENTS', 'Peut-on commenter les Q&#38;R ?');
define('_AM_SF_ANSWER', 'R&#233;ponse Propos&#233;e');
define('_AM_SF_ANSWER_APPROVED_NEED_APPROVED', 'La R&#233;ponse a &#233;t&#233; approuv&#233;e. La Q&#38;R doit maintenant &#234;tre vis&#233;e par un mod&#233;rateur.');
define('_AM_SF_ANSWER_APPROVED_PUBLISHED', 'La R&#233;ponse a &#233;t&#233; approuv&#233;e et la Q&#38;R a &#233;t&#233; publi&#233;e.');
define('_AM_SF_ANSWER_OFFICIAL', 'R&#233;ponse Officielle');
define('_AM_SF_ANSWER_REJECTED', 'La R&#233;ponse a &#233;t&#233; rejet&#233;e.');
define('_AM_SF_ANSWER_REJECTED_OPEN_QUESTION', 'La R&#233;ponse a &#233;t&#233; rejet&#233;e et la question est &#224; pr&#233;sent dirig&#233;e vers la Section Question ouverte pour qu&#39;un autre utilisateur puisse y r&#233;pondre.');
define('_AM_SF_ANSWER_DELETE_ERROR', 'Une erreur s&#39;est produite &#224; l&#39;effacement de la r&#233;ponse');
define("_AM_SF_ANSWERED_APPROVE_SUCCESS", "La r&#233;ponse a &#233;t&#233; revue et le Q&#38;A <br />a &#233;t&#233; publi&#233;e dans la section publique du site.");
define("_AM_SF_ANSWERED_BY", "Question r&#233;pondue par : ");
define("_AM_SF_ANSWERED_TITLE", "Questions ouvertes ayant re&#231;u des r&#233;ponses");
define("_AM_SF_ANSWERED_TITLE_INFO", "Cette question ouverte a re&#231;u une r&#233;ponse. Vous pouvez &#233;diter le Q&#38;A ici. Celle ci approuv&#233;e, la Q&#38;A sera publi&#233;e dans la section publique du site.");
define('_AM_SF_ANSWERING', 'R&#233;pondre');
define('_AM_SF_ANSWERED', 'R&#233;pondu');
define('_AM_SF_ANSWERED_EXP', '<strong>R&#233;ponses aux Questions</strong> : Questions de la section des Questions ouvertes  ayant re&#231;u des r&#233;ponses de la part les utilisateurs. La R&#233;ponse Approuv&#233;e, la Question devient une Q&#38;R qui se doit d&#39;&#234;tre tout autant Approuv&#233;e. ');
define('_AM_SF_ANSWERED_MODERATE', 'Mod&#233;rer la R&#233;ponse &#224; cette Question');
define('_AM_SF_ANSWERISDELETED', 'La R&#233;ponse a &#233;t&#233; effac&#233;e');
define('_AM_SF_ANSWERNOTFOUND', 'Erreur : Aucune R&#233;ponse Officielle');
define('_AM_SF_APPROVE', 'Approuver');
define('_AM_SF_APPROVED', 'R&#233;ponse Approuv&#233;e');
define('_AM_SF_APPROVED_INFO', 'La R&#233;ponse &#224; cette Question a &#233;t&#233; Approuv&#233;e. Cette Question devient alors promue &#224; l&#39;&#233;tat de  Q&#38;R soumis et se doit d&#39;&#234;tre approuv&#233;e afin d&#39;&#234;tre publi&#233;e dans la Section des Q&#38;R.');
define("_AM_SF_APPROVED_MODERATE", "Mod&#233;rer cette proposition de Q&#38;R");
define('_AM_SF_APPROVED_TITLE', 'R&#233;ponse Approuv&#233;e');
define('_AM_SF_APPROVESUB', 'Approuver la Proposition');
define('_AM_SF_APPROVING', 'Approbation');
define("_AM_SF_ANSWER_FAQ", "R&#233;ponse<span style='font-size: xx-small; font-weight: normal; display: block;'>R&#233;ponse d&#233;taill&#233;e se rapportant &#224; la Question.</span>");
define('_AM_SF_ARTCOLNAME', 'Cat&#233;gorie');
define('_AM_SF_ARTCREATEDOK', 'La Q&#38;R a &#233;t&#233; approuv&#233;e et publi&#233;e dans la Section des Q&#38;R');
define('_AM_SF_ARTID', 'N&#176;');
define('_AM_SF_ARTISDELETED', 'La Q&#38;R a &#233;t&#233; effac&#233;e');
define('_AM_SF_ARTMODIFIED', 'La Q&#38;R a &#233;t&#233; modifi&#233;e');
define('_AM_SF_ARTNOTCREATED', 'D&#233;sol&#233;. Il a &#233;t&#233;  impossible de cr&#233;er cette Q&#38;R!');
define('_AM_SF_ARTNOTUPDATED', 'D&#233;sol&#233;. Il &#233;t&#233; impossible de mettre &#224; jour cette Q&#38;R');
define("_AM_SF_ASC", "Ascendant");
define('_AM_SF_ASKED', 'Demand&#233;');
define("_AM_SF_ASKED_APPROVE_SUCCESS", "La question pos&#233;e a re&#231;u une r&#233;ponse et la Q&#38;A a &#233;t&#233; publi&#233;e dans la section publique du site.");
define('_AM_SF_ASKED_EXP', '<strong>Questions Pos&#233;es</strong> : Questions pos&#233;es par les utilisateurs. Les Questions n&#39;ont pas encore &#233;t&#233; approuv&#233;es par un mod&#233;rateur. Une fois approuv&#233;es, les <i>Questions Pos&#233;es</i> deviendront des <i>Questions Ouvertes</i> et seront dirig&#233;es vers la Section des <strong>Questions Ouvertes</strong>');
define("_AM_SF_ASKED_TITLE", "Question pos&#233;e");
define("_AM_SF_ASKED_TITLE_INFO", "Ceci est une question pos&#233;e par un utilisateur. Vous pouvez r&#233;viser la question et &#233;crire la r&#233;ponse.<br />Ceci approuv&#233;, la Q&#38;A sera publi&#233;e dans la section publique du site.");
define('_AM_SF_AUTHFAQ', 'Publier la R&#233;ponse soumise');
define('_AM_SF_AUTHORIZE', 'Autoriser');
define('_AM_SF_BACK2IDX', 'Abandonn&#233;. Vous renvoie &#224; l&#39;index');
define('_AM_SF_BLOCKS', 'Gestion des Blocs');
define('_AM_SF_BLOCKSTXT', 'Ce module dispose des blocs suivants, que vous pouvez g&#233;rer ici ou dans le syst&#232;me de gestion des blocs.');
define('_AM_SF_BLOCKSANDGROUPS', 'Blocs et Groupes');
define('_AM_SF_BLOCKSGROUPSADMIN', 'Gestion des Blocs et des Groupes');
define('_AM_SF_BY', 'par');
define('_AM_SF_CANCEL', 'Abandonner');
define('_AM_SF_CATCREATED', 'Une Nouvelle Cat&#233;gorie a &#233;t&#233; cr&#233;&#233;e et sauvegard&#233;e');
define('_AM_SF_CATEGORIES_DSC', 'Vous retrouvez ici la liste des Cat&#233;gories cr&#233;&#233;es du Module');
define('_AM_SF_CATEGORIES_TITLE', 'Cat&#233;gories Cr&#233;&#233;es');
define('_AM_SF_CATEGORY', 'Cat&#233;gorie');
define('_AM_SF_CATEGORY_CREATE', 'Cr&#233;er une Cat&#233;gorie');
define("_AM_SF_CATEGORY_FAQ", "Cat&#233;gorie<span style='font-size: xx-small; font-weight: normal; display: block;'>Cat&#233;gorie se rapportant &#224; cette Q&#38;R.</span>");
define("_AM_SF_CATEGORY_QUESTION", "Cat&#233;gorie<span style='font-size: xx-small; font-weight: normal; display: block;'>Cat&#233;gorie &#224; laquelle appartient cette question.</span>");
define('_AM_SF_CATEGORY_SAVE_ERROR', 'Une erreur est survenue lors de la sauvegarde des Cat&#233;gories. Vous retrouvez ici la liste des erreurs');
define('_AM_SF_CLEAR', 'Nettoyer');
define('_AM_SF_COLDESCRIPT', 'Description de Cat&#233;gorie');
define('_AM_SF_COLISDELETED', 'La Cat&#233;gorie %s a &#233;t&#233; Effac&#233;e');
define('_AM_SF_COLMODIFIED', 'La Cat&#233;gorie a &#233;t&#233; Modifi&#233;e');
define('_AM_SF_COLPOSIT', 'Position de Cat&#233;gorie');
define('_AM_SF_CATEGORIES', 'Cat&#233;gories');
define('_AM_SF_CATHEADER', 'Gestion des Cat&#233;gories');
define('_AM_SF_CONTEXTMODULELINK', 'Li&#233;(e) contextuellement &#224; ce Module');
define("_AM_SF_CONTEXTMODULELINK_FAQ", "Contexte li&#233; &#224; ce Module<span style='font-size: xx-small; font-weight: normal; display: block;'>S&#233;lectionnez le Module avec lequel cette Q&#38;R sera<br />li&#233;e. Si le Bloc de Contexte de Q&#38;R est visible<br />pour ce module, la phrase du &#39;Comment fais-je&#39; de <br />cette Q&#38;R sera affich&#233;e.</span>");
define('_AM_SF_CONTEXTOPTIONS', 'Options de Contexte');
define('_AM_SF_CONTEXTPAGE', 'Li&#233;(e) contextuellement &#224; cette URL');
define('_AM_SF_CONTEXTURLLINK', 'Lier &#224; cette URL');
define('_AM_SF_CREATE', 'Cr&#233;er');
define('_AM_SF_CREATED', 'Cr&#233;&#233;(e)');
define('_AM_SF_CREATEART', 'Cr&#233;er une Q&#38;R');
define('_AM_SF_CREATESMARTFAQ', 'Cr&#233;er une nouvelle Q&#38;R');
define('_AM_SF_CREATEQUESTION', 'Cr&#233;er une Question Ouverte');
define('_AM_SF_CREATECATEGORY', 'Cr&#233;er une Nouvelle Cat&#233;gorie');
define('_AM_SF_CREATEIN', 'Cr&#233;er dans la Cat&#233;gorie');
define('_AM_SF_CREATINGNEW', 'Cr&#233;er un Nouveau');
define('_AM_SF_CREATEFAQ', 'Cr&#233;er une Nouvelle Q&#38;R');
define('_AM_SF_DELETE', 'Effacer');
define('_AM_SF_DELETEART', 'Effacer la Q&#38;R');
define('_AM_SF_DELETE_CAT_CONFIRM', 'Veuillez consid&#233;rer qu&#39;en effa&#231;ant une Cat&#233;gorie, que toutes les Sous Cat&#233;gories et Q&#38;R attach&#233;es, ainsi que tous les commentaires attach&#233;s seront effac&#233;s. Etes vous vraiment certain de d&#233;sirer effacer cette Cat&#233;gorie ?');
define('_AM_SF_DELETE_CAT_ERROR', 'Erreur rencontr&#233;e &#224; l&#39;effacement de cette Cat&#233;gorie');
define('_AM_SF_DELETECOL', 'Effacer une Cat&#233;gorie');
define('_AM_SF_DELETESUBM', 'Effacer une Proposition');
define('_AM_SF_DELETETHISARTICLE', 'Effacer cette Q&#38;R ?');
define('_AM_SF_DELETETHISANSWER', 'Effacer cette R&#233;ponse ?');
define('_AM_SF_DELETETHISQUESTION', 'Effacer cette Question ?');
define('_AM_SF_DELETEQUESTION', 'Effacer une Question');
define("_AM_SF_DESC", "Descendant");
define('_AM_SF_DESCRIP', 'Description de la Cat&#233;gorie ');
define('_AM_SF_DIDUNO', 'Le Saviez-Vous ?');
define("_AM_SF_DIDUNO_FAQ", "Le Saviez vous ?<span style='font-size: xx-small; font-weight: normal; display: block;'>Sera utilis&#233; dans le bloc le Saviez Vous.</span>");
define('_AM_SF_DOCONTEXT', 'Donner un contexte &#224; cette Q&#38;R');
define('_AM_SF_DOHTML', 'Autoriser les balises HTML');
define('_AM_SF_DOSMILEY', 'Autoriser les emotic&#244;nes');
define('_AM_SF_DOXCODE', 'Autoriser les codes XOOPS');
define('_AM_SF_EDITART', 'Editer une Q&#38;R');
define('_AM_SF_EDITCOL', 'Editer une Cat&#233;gorie');
define('_AM_SF_EDITING', 'Edition');
define('_AM_SF_EDITING_INFO', 'Vous pouvez &#233;diter cette question. Les modifications apport&#233;es prendront imm&#233;diatement effet dans la section des Questions Ouvertes.');
define('_AM_SF_EDITQUES', 'Editer la question');
define('_AM_SF_EDITSUBM', 'Editer la Proposition');
define('_AM_SF_ERROR', 'Une erreur s&#39;est produite');
define('_AM_SF_ERROR_ANSWER_NOT_SAVED', 'Une erreur s&#39;est produite. La r&#233;ponse n&#39;a pas &#233;t&#233; sauvegard&#233;e dans la base de donn&#233;es');
define('_AM_SF_ERROR_FAQ_NOT_SAVED', 'Une erreur s&#39;est produite. La Q&#38;R n&#39;a pas &#233;t&#233; sauvegard&#233;e dans la Base de donn&#233;es');
define("_AM_SF_EXACTURL", "URL Exacte ?<span style='font-size: xx-small; font-weight: normal; display: block;'>Si ce param&#232;tre est &#39;Oui&#39;, &#39;l&#39;URL Sp&#233;cifique&#39; ci-dessus devra correspondre exactement &#224; l&#39;URL courante pour que la Q&#38;R soit affich&#233;e. <br />Si le Param&#232;tre est &#39;Non&#39;, la Q&#38;R sera affich&#233;e si cette &#39;URL Sp&#233;cifique&#39; correspond &#224; une partie de l&#39;URL courante. (modules/newbb/*.php)</span>");

define('_AM_SF_FAQ_EDIT', 'Editer cette Q&#38;R');
define("_AM_SF_FAQ_NEW_ANSWER_PUBLISHED", "La réponse originale a été remplacée par cette réponse.");
define("_AM_SF_FAQ_REVIEW", "Modifier cette r&#233;ponse avant approbation");
define("_AM_SF_FAQ_MERGE", "Fusionner la r&#233;ponse originale et la nouvelle r&#233;ponse");
define("_AM_SF_FAQ_APPROVE_NEW_ANSWER", "Approuver cette nouvelle réponse sans l'examiner");
define('_AM_SF_GOMOD', 'Acc&#233;der au Module');
define('_AM_SF_GROUPS', 'Gestion des Groupes');
define('_AM_SF_GROUPSINFO', 'Configure les droits du Module et des Blocs pour chaque Groupe');
define('_AM_SF_HELP', 'Aide');
define('_AM_SF_HOWDOI', 'Comment fais je ...');
define("_AM_SF_HOWDOI_FAQ", "Comment fais-je ...<span style='font-size: xx-small; font-weight: normal; display: block;'>sera utilis&#233; dans le block contextuel de la Q&#38;R.<br />ce devrait &#234;tre une version courte de la Question.</span>");
define('_AM_SF_ID', 'N&#176;');
define('_AM_SF_IMPORT', 'Importer');
define('_AM_SF_IMPORT_ALL_QUESTIONS', 'Toutes les Questions');
define('_AM_SF_IMPORT_ALLOWCOMMENTS', 'Les Q&#38;R peuvent-elles &#234;tre comment&#233;es ?');
define('_AM_SF_IMPORT_ANSWER_ERROR', 'Une erreur s&#39;est produite au chargement de la R&#233;ponse <em>%s</em>.');
define('_AM_SF_IMPORT_AUTOAPPROVE', 'Auto-Approbation');
define('_AM_SF_IMPORT_BACK', 'Retour &#224; la page d&#39;Importation');
define('_AM_SF_IMPORT_CATEGORY_ERROR', 'Une Erreur s&#39;est produite au chargement de la Cat&#233;gorie <em>%s</em>.');
define('_AM_SF_IMPORT_CATEGORY_SUCCESS', 'La Cat&#233;gorie <em>%s</em> &#224; &#233;t&#233; import&#233;e avec succ&#232;s.');
define('_AM_SF_IMPORT_CATEGORIES', '%s Cat&#233;gories');
define("_AM_SF_IMPORT_CATEGORY_FAQ", "Une erreur &#224; &#233;t&#233; produite pendant l&#39;importation des FAQq <em>%s</em>.");
define('_AM_SF_IMPORT_ERROR', 'Une Erreur s&#39;est produite &#224; l&#39;Importation de la Q&#38;R');
define("_AM_SF_IMPORT_FILE_NOT_FOUND", "Fichier d&#39;import non trouv&#233; sur <strong>%s</strong>");
define('_AM_SF_IMPORT_FROM', 'Importation de %s');
define("_AM_SF_IMPORT_INFO", "Vous pouvez directement importer les param&#232;tres de la Q&#38;R vers le module. Choisissez simplement le param&#232;tre que vous d&#233;sirez importer et cliquez sur le bouton &#39;Importer&#39;.");
define('_AM_SF_IMPORT_MODULE_FOUND', '%s module a &#233;t&#233; trouv&#233;. il y a %s Cat&#233;gories et %s Q&#38;R.');
define("_AM_SF_IMPORT_MODULE_FOUND_NO_FAQ", "%s module a &#233;t&#233;. Il y a %s cat&#233;gories mais aucune FAQ n&#39;a &#233;t&#233; import&#233;e.");
define('_AM_SF_IMPORT_NO_CATEGOY', 'Il n&#39;y a pas de Cat&#233;gories &#224; Importer');
define("_AM_SF_IMPORT_NO_MODULE", "XoopsFAQ ou WF-FAQ n&#39;&#233;tant pas install&#233; sur ce site, vous ne pouvez pas acc&#233;der aux options d&#39;importations.");
define('_AM_SF_IMPORT_ONLY_VISIBLE', 'Seulement les Questions visibles');
define('_AM_SF_IMPORT_PARENT_CATEGORY', 'SmartFAQ Cat&#233;gorie parente');
define("_AM_SF_IMPORT_PERMISSIONS", "Permissions<span style='font-size: xx-small; font-weight: normal; display: block;'>Groupes qui auront les permissions n&#233;c&#233;ssaires &#224; pouvoir visualiser ces Q&#38;R import&#233;es.<br />Cette Q&#38;R.</span>");
define('_AM_SF_IMPORT_RESULT', 'Voici les r&#233;sultats de l&#39;importation.');
define('_AM_SF_IMPORT_SETTINGS', 'Param&#232;tre d&#39;Importation');
define('_AM_SF_IMPORT_SUCCESS', 'Les Param&#232;tres de la Q&#38;R ont &#233;t&#233; charg&#233;s avec succ&#232;s dans le module.');
define('_AM_SF_IMPORT_TITLE', 'Importer une Q&#38;R');
define("_AM_SF_IMPORT_WFFAQ_105", "FAQs depuis WF-FAQ 1.0.5");
define("_AM_SF_IMPORT_XOOPSFAQ_110", "FAQs depuis XoopsFAQ 1.1");
define('_AM_SF_IMPORTED_CATEGORIES', 'Cat&#233;gories import&#233;es : %s');
define('_AM_SF_IMPORTED_QUESTION', 'Importation de Questions : <em>%s</em>');
define('_AM_SF_IMPORTED_QUESTIONS', 'Questions import&#233;es : <em>%s</em>');
define('_AM_SF_IMPORTED_USER', 'Soumis et R&#233;pondu par');
define('_AM_SF_IMPORT_SELECTION', "S&#233;lection d&#39;Importation");
define("_AM_SF_IMPORT_SELECT_FILE", "Param&#232;tre de Q&#38;R<span style='font-size: xx-small; font-weight: normal; display: block;'>Choisissez le param&#232;tre de Q&#38;R que vous d&#233;sirez importer dans le module.</span>");
define('_AM_SF_INDEX', 'Index');
define('_AM_SF_INVENTORY', 'R&#233;sum&#233; du Module');
define('_AM_SF_MODADMIN', 'Admin du Module : ');
define('_AM_SF_MODART', 'Modifiez une Q&#38;R');
define('_AM_SF_MODCOL', 'Modifiez une Cat&#233;gorie existante');
define("_AM_SF_MODERATORS_DEF", "Mod&#233;rateurs<span style='font-size: xx-small; font-weight: normal; display: block;'>Utilisateurs qui peuvent agir en mod&#233;rateur pour cette<br />Cat&#233;gorie. Ils seront habilit&#233;s &#224; ajouter, &#233;diter,<br />approuver et effacer les questions et les Q&#38;R<br />contenues dans cette Cat&#233;gorie.</span>");
define('_AM_SF_MODIFY', 'Modifier');
define('_AM_SF_MODIFYCOL', 'Modifier une Cat&#233;gorie');
define('_AM_SF_MODIFYTHISCOL', 'Modifier cette cat&#233;gorie ?');
define('_AM_SF_MODULEHEAD', "R&#233;sum&#233;s et question/réponse dans chaque statut");
define('_AM_SF_NEED_CATEGORY_FAQ', 'Pour Cr&#233;er une Q&#38;R, vous devez en premier lieu Cr&#233;er une Cat&#233;gorie');
define('_AM_SF_NEED_CATEGORY_QUESTION', 'Pour Cr&#233;er une Question, Vous devez en premier lieu Cr&#233;er une Cat&#233;gorie');
define('_AM_SF_NEWANSWER', 'Nouvelle R&#233;ponse');
define('_AM_SF_NEW_ANSWER', 'Nouvelle R&#233;ponse');
define('_AM_SF_NEW_ANSWER_EXP', '<strong>Nouvelle R&#233;ponse</strong> : Une nouvelle R&#233;ponse &#224; &#233;t&#233; &#233;mise par un Utilisateur au sujet d&#39;une Q&#38;R publi&#233;e. Une fois cette R&#233;ponse valid&#233;e cette derni&#232;re devient la R&#233;ponse officielle &#224; la Question');
define("_AM_SF_NEW_ANSWER_EDITING", "Editer une Q&#38;A avec une nouvelle r&#233;ponse");
define("_AM_SF_NEW_ANSWER_EDITING_INFO", "Une nouvelle r&#233;ponse a &#233;t&#233; soumise pour cette Q&#38;A. Vous pouvez l'&#233;diter ici. Quand vous publiez cette Q&#38;A, la nouvelle r&#233;ponse remplacera l&#39;originale.");
define('_AM_SF_NEWART', 'Cr&#233;er une nouvelle Q&#38;R');
define("_AM_SF_NEW_CONTRIBUTION", "--- d&#233;tails additionnels soumis par %s sur %s\n\n%s");
define('_AM_SF_NEWQUESTION', 'Cr&#233;er une nouvelle Question');
define('_AM_SF_NO', 'Non');
define('_AM_SF_NO_NEWANSWERS', 'Il n&#39;y a actuellement aucune R&#233;ponse aux Q&#38;R publi&#233;es');
define('_AM_SF_NOFAQS', 'il n&#39;y a actuellement aucune Q&#38;R publi&#233;e');
define('_AM_SF_NOFOUND', 'Aucun utilisateur ne correspond &#224; cette requ&#234;te');
define('_AM_SF_NONE', 'Aucune');
define('_AM_SF_NOPERMSSET', 'Aucune Permission ne peut &#234;tre param&#233;tr&#233;e. Il n&#39;y a pas de Cat&#233;gorie! Veuillez Cr&#233;er une Cat&#233;gorie dans un premier temps');
define('_AM_SF_NOS', 'Aucune Q&#38;R n&#39;est &#224; visualiser pour le moment');
define('_AM_SF_NOCAT', 'Aucune Cat&#233;gorie &#224; visualiser');
define('_AM_SF_NOCATSELECTED', 'Aucune Cat&#233;gorie s&#233;lectionn&#233;e');
define('_AM_SF_NOCOLTOEDIT', 'Aucune Cat&#233;gorie n&#39;est &#224; &#233;diter!');
define('_AM_SF_NOFAQSELECTED', 'Aucune Q&#38;R s&#233;lectionn&#233;e');
define('_AM_SF_NOANSWERS', 'Aucune R&#233;ponse trouv&#233;');
define('_AM_SF_NOANSWERYET', 'Aucune R&#233;ponse en Attente d&#39;approbation actuellement');
define('_AM_SF_NOQUEUED', 'Aucune Question Ouverte actuellement');
define('_AM_SF_NOREQUESTYET', 'Aucune Demande en Attente d&#39;Approbation actuellement');
define('_AM_SF_NOSUBMISSYET', 'Aucune Soumission en Attente d&#39;Approbation Actuellement');
define('_AM_SF_NOTUPDATED', 'Une Erreur s&#39;est produite lors de la mise &#224; jour de la Base de Donn&#233;es');
define('_AM_SF_OFFLINE', 'Hors ligne');
define('_AM_SF_OFFLINE_EXP', '<strong>Q&#38;R Hors ligne</strong> : Q&#38;R mise Hors ligne temporairement ou non. Les Q&#38;R Hors ligne ne seront plus montr&#233;es dans la section des Q&#38;R');
define("_AM_SF_OFFLINE_FIELD", "Hors ligne<span style='font-size: xx-small; font-weight: normal; display: block;'>S&#233;lectionnez &#39;Non&#39; pour renvoyer cette Q&#38;R<br />en ligne dans la Section des Q&#38;R.</span>");
define('_AM_SF_OFFLINEEDITING', 'Editer une Q&#38;R hors ligne');
define("_AM_SF_OFFLINEEDITING_INFO", "Vous pouvez Editer cette Q&#38;R hors ligne. Les Modifications seront sauvegard&#233;es pour cet article. Aussi, Si vous d&#233;sirez montrer cette Q&#38;R dans la Section des Q&#38;R, Vous devrez param&#233;trer le champ <strong>Hors Ligne</strong> &#224; &#39;Non&#39;.");
define('_AM_SF_OPEN_QUESTION', 'Question ouverte');
define('_AM_SF_OPEN_QUESTIONS', 'Questions ouvertes');
define('_AM_SF_OPENED', 'Ouverte');
define("_AM_SF_OPEN_QUESTION_EDIT", "R&#233;pondre &#224; cette question");
define('_AM_SF_OPENED_TITLE', 'Questions Publi&#233;es dans la Section des Questions Ouvertes');
define('_AM_SF_OPENED_DSC', 'Voici la liste de toutes les Questions publi&#233;es dans la Section des Questions Ouvertes.');
define('_AM_SF_OPENED_EXP', '<strong>Questions Ouvertes</strong> : Questions pos&#233;es par un Utilisateur et approuv&#233;es par un Mod&#233;rateur. Ces Questions ont &#233;t&#233; dirig&#233;es vers la Section des <i>Questions Ouvertes</i> du Module. Attendez que les Utilisateurs y r&#233;pondent eux-m&#234;mes.');
define('_AM_SF_OPTIONS', 'Options');
define('_AM_SF_OPTS', 'Pr&#233;f&#233;rences');
define('_AM_SF_OPEN_QUESTION_ANSWERING', 'R&#233;pondre &#224; une Question Ouverte');
define('_AM_SF_OPEN_QUESTION_ANSWERING_INFO', 'Vous r&#233;pondez &#224; une question ouverte, qui deviendra une Q&#38;R et sera publi&#233;e dans la Section des Q&#38;R.');
define('_AM_SF_OPENED_ANSWERING_SUCCESS', 'Une r&#233;ponse &#224; une Question ouverte a &#233;t&#233; &#233;mise et publi&#233;e dans la Section Q&#38;R');
define("_AM_SF_PARENT_CATEGORY_EXP", "Cat&#233;gorie Parente<span style='font-size: xx-small; font-weight: normal; display: block;'>Cette Cat&#233;gorie est-elle une sous Cat&#233;gorie ?<br />Si oui, s&#233;lectionnez la Cat&#233;gorie qui<br />sera en relation avec cette pr&#233;sente Cat&#233;gorie.</span>");
define('_AM_SF_PERMISSIONS', 'Permissions');
define("_AM_SF_PERMISSIONS_FAQ", "Permissions<span style='font-size: xx-small; font-weight: normal; display: block;'>Groupes qui auront les droits de visualisation pour<br />cette Q&#38;R.</span>");
define("_AM_SF_PERMISSIONS_QUESTION", "Permissions<span style='font-size: xx-small; font-weight: normal; display: block;'>Groupes qui auront les droits n&#233;cessaires &#224; la visualisation de cette Question.</span>");
define("_AM_SF_PERMISSIONS_CAT_READ", "Droits de lecture<span style='font-size: xx-small; font-weight: normal; display: block;'>Groupes disposant des permissions requises &#224; la visualisation de cette Cat&#233;gorie, aussi bien que de n&#39;importe quelle Question Ouverte et Q&#38;R dans cette Cat&#233;gorie.</span>");
define("_AM_SF_PERMISSIONS_APPLY_ON_FAQS", "Appliquer les permissions de lecture de Q&#38;R<span style='font-size: xx-small; font-weight: normal; display: block;'>Appliquer les permissions de lecture ci-dessus sur toutes les Q&#38;R de cette cat&#233;gorie, &#233;crasant les permissions globales des Q&#38;R.</span>");
define('_AM_SF_PERMISSIONSADMIN', 'Gestion des Droits');
define('_AM_SF_PERMISSIONSVIEWMAN', 'Droits de Visualisation des Cat&#233;gories');
define('_AM_SF_PERMISSIONSADMINMAN', 'Droits de Mod&#233;rations des Cat&#233;gories');
define("_AM_SF_POSITION", "Position");
define('_AM_SF_PUBLISH', 'Publier');
define('_AM_SF_PUBLISHED', 'Publi&#233;');
define('_AM_SF_PUBLISHED_DSC', 'Voici la liste de toutes les Q&#38;R Publi&#233;es disponibles dans la Section des Q&#38;R.');
define('_AM_SF_PUBLISHED_EXP', '<strong>Q&#38;R Publi&#233;s</strong> : Q&#38;R Approuv&#233;es, et transmises &#224; la Section des Q&#38;R');
define('_AM_SF_PUBLISHED_MOD_SUCCESS', 'La Q&#38;R a &#233;t&#233; modifi&#233;e avec Succ&#232;s');
define('_AM_SF_PUBLISHEDANSWER', 'R&#233;ponse Publi&#233;e');
define('_AM_SF_PUBLISHEDNEWANSWER', 'R&#233;ponse(s) soumise(s) r&#233;cente(s) de Q&#38;R Publi&#233;es');
define('_AM_SF_PUBLISHEDFAQS', 'Q&#38;R Publi&#233;es');
define("_AM_SF_PUBLISHEDFAQS_CAT", "Q&#38;R de cette cat&#233;gorie");
define("_AM_SF_PUBLISHED_CAT_DSC", "Voici la liste des Q&#38;R publi&#233;es dans cette cat&#233;gorie.");
define('_AM_SF_PUBLISHEDEDITING', 'Edition d&#39;une Q&#38;R Publi&#233;e');
define('_AM_SF_PUBLISHEDEDITING_INFO', 'Vous pouvez &#233;diter cette Q&#38;R. Les modifications seront imm&#233;diatement prises en compte dans la section des Q&#38;R.');
define('_AM_SF_QUESTION', 'Question');
define('_AM_SF_QUESTION_APPROVING', 'Approuver une Question');
define('_AM_SF_QUESTION_APPROVING_INFO', 'Revoir l&#39;ordre de Publication de cette Question dans la Section des Questions Ouvertes. Les autres utilisateurs auront alors la possibilit&#233; de proposer des r&#233;ponses &#224; cette question.');
define('_AM_SF_QUESTION_EDIT', 'Editer cette Question');
define('_AM_SF_QUESTION_MODERATE', 'Mod&#233;rez cette Question');
define('_AM_SF_QUESTIONCREATEDOK', 'La Question a &#233;t&#233; cr&#233;&#233;e avec succ&#232;s et ajout&#233;e &#224; la Section des Questions Ouvertes!');
define('_AM_SF_QUESTIONISDELETED', 'La Question a &#233;t&#233; Effac&#233;e.');
define('_AM_SF_QUESTIONHEADER', 'Gestion des Questions');
define('_AM_SF_QUESTIONMODIFIED', 'La Question a &#233;t&#233; Modifi&#233;e avec succ&#232;s!');
define('_AM_SF_QUESTIONNOTCREATED', 'D&#233;sol&#233;. Il n&#39;a pas &#233;t&#233; possible de Cr&#233;er cette Question!');
define('_AM_SF_QUESTIONNOTUPDATED', 'D&#233;sol&#233;. Il n&#39; a pas &#233;t&#233; possible de mettre &#224; jour cette Question!');
define('_AM_SF_QUESTIONPUBLISHED', 'La Question a &#233;t&#233; Publi&#233;e dans la Section des Questions Ouvertes.');
define('_AM_SF_QUESTIONS', 'Questions');
define('_AM_SF_QUESTION_AFFIRMATION', 'Question ou Affirmation');
define('_AM_SF_QUEUE', 'Publier dans les Questions Ouvertes');
define('_AM_SF_REJECTED_EDIT', 'Editez cette Q&#38;R rejet&#233;e');
define('_AM_SF_REQUEST_QUEUE', 'La Question a &#233;t&#233; ajout&#233;e avec succ&#232;s dans la Section des Questions Ouvertes ');
define('_AM_SF_REJECTED_QUESTION', 'Question Rejet&#233;e');
define('_AM_SF_REJECTED_QUESTION_EXP', '<strong>Question Rejet&#233;e</strong> : Questions &#233;mises par un Utilisateur, Rejet&#233;e par un Mod&#233;rateur. Les Questions Rejet&#233;es ne sont pas montr&#233;es &#224; la Section des Questions Ouvertes.');
define('_AM_SF_REJECTED_SMARTFAQ', 'Q&#38;R Rejet&#233;e');
define('_AM_SF_REJECTED_SMARTFAQ_EXP', '<strong>Q&#38;R Rejet&#233;e</strong> : Q&#38;R propos&#233;es par un Utilisateur, rejet&#233;es par un Mod&#233;rateur. Les Q&#38;R rejet&#233;es ne sont pas montr&#233;es dans la Section des Q&#38;R');
define("_AM_SF_REQUESTED_BY", "Question demand&#233;e par : ");
define("_AM_SF_SELECT_SORT", "Ordre de tri : ");
define('_AM_SF_SELECT_STATUS', 'Choisissez un statut');
define('_AM_SF_SHOWING', '&#201;tat s&#233;lectionn&#233; : ');
define('_AM_SF_SHOWREQUEST', 'Demande de Question en attente de publication dans la Section des Questions Ouvertes.');
define('_AM_SF_SHOWSUBMITED_ANSWERS', 'Soumission de R&#233;ponse en Attente d&#39;Approbation.');
define('_AM_SF_SHOWSUBMISSIONS', 'Proposition de Q&#38;R en attente de Publication');
define('_AM_SF_SMARTFAQ', 'Q&#38;R');
define('_AM_SF_SMARTFAQS', 'Q&#38;R');
define('_AM_SF_SMARTFAQ_APPROVING', 'Approbation de Q&#38;R');
define("_AM_SF_STATUS_EXP", "Statuts<span style='font-size: xx-small; font-weight: normal; display: block;'>S&#233;lectionnez le statut de la Q&#38;R.</span>");
define('_AM_SF_SUBMISSIONSMNGMT', 'Proposition de Q&#38;R');
define('_AM_SF_SPECIFIC_URL_SELECT', 'URL Sp&#233;cifique ...');
define('_AM_SF_SPECIFIC_URL', 'URL Sp&#233;cifique : </span><span style=&#39;font-size: xx-small; font-weight: normal; display: block;&#39;> Si vous avez choisi <i>'. _AM_SF_SPECIFIC_URL_SELECT . '</i> dans le "Contexte li&#233; &#224; ce module" ci-dessus, veuillez en sp&#233;cifier l&#39;URL.<br /><strong>Exemple : </strong> modules/newbb</span>');
define("_AM_SF_SUBMISSION_MODERATE", "Mod&#233;rer cette Proposition de Q&#38;R");
define('_AM_SF_SUBMITTED', 'Propos&#233;');
define('_AM_SF_SUBMITTED_EXP', '<strong>Propositions de Q&#38;R</strong> : Q&#38;R propos&#233;es par les Utilisateurs. Une fois approuv&#233;s ces derni&#232;res seront montr&#233;es dans la Section des Q&#38;R.');
define('_AM_SF_SUBMITTED_ANSWER', 'Proposition de R&#233;ponse');
define('_AM_SF_SUBMITTED_ANSWER_ACCEPTED', 'La R&#233;ponse propos&#233;e a &#233;t&#233; Approuv&#233;e.');
define('_AM_SF_SUBMITTED_ANSWER_INFO', 'Voici la liste des propositions de R&#233;ponses  pour cette question. Choisissez-en une qui sera la R&#233;ponse Officielle &#224; cette Question.');
define("_AM_SF_SUBMITTED_INFO", "Cette Q&#38;R a &#233;t&eacutee; soumise par un membre. Vous pouvez faire autant de modifications que vous le d&#233;sirez. Une fois approuv&#233;e, cette Q&#38;R sera montr&#233;e dans la Section des Q&#38;R de ce site.");
define('_AM_SF_SUBMITTED_APPROVE_SUCCESS', 'La Q&#38;R  propos&#233;e a &#233;t&#233; Publi&#233;e dans la Section des Q&#38;R.');
define('_AM_SF_SUBMITTED_TITLE', 'Approuver une proposition de Q&#38;R');
define('_AM_SF_FAQ_DELETE_ERROR', 'Une erreur est apparue lors de l&#39;effacement de la Q&#38;R.');
define('_AM_SF_TOTALPUBLISHED', 'Publi&#233;es : ');
define('_AM_SF_TOTALCAT', 'Cat&#233;gories : ');
define('_AM_SF_TOTALNEWANSWERS', 'Nouvelles R&#233;ponses : ');
define('_AM_SF_TOTALSUBMITTED', 'Propos&#233;s : ');
define('_AM_SF_TOTALOPENED', 'Ouverts : ');
define('_AM_SF_TOTALASKED', 'Demandes : ');
define('_AM_SF_VIEW_CATS', 'S&#233;lectionnez les Cat&#233;gories que chaque Groupe pourra Visualiser');
define('_AM_SF_WEIGHT', 'Poids');
define('_AM_SF_XOOPS_QA', 'XOOPS Q&#38;R');
define('_AM_SF_YES', 'Oui');
define("_AM_SF_PARTIALVIEW", "Permettre aux anonymes d&#39;avoir une vue partielle de la r&#233;ponse");

// Search users
define("_AM_SF_FINDUSERS", "Recherche d&#39;Utilisateurs");
define('_AM_SF_UNAME', 'Nom d&#39;Utilisateur');
define('_AM_SF_REALNAME', 'Nom r&#233;el');
define('_AM_SF_LIMIT', 'Utilisateurs par page');
define('_AM_SF_SUBMIT', 'Valider');
define('_AM_SF_RESULTS', 'R&#233;sultats de la Recherche');
define('_AM_SF_ACTIVEUSERS', 'Utilisateurs actifs : %s');
define('_AM_SF_INACTIVEUSERS', 'Utilisateurs inactifs : %s');

// New table
define('_AM_SF_FAQID', 'N&#176;');
define('_AM_SF_FAQCAT', 'Cat&#233;gorie');
define('_AM_SF_STATUS', 'Statuts');
define('_AM_SF_NOFAQSSEL', 'D&#233;sol&#233;.  Aucun article dans l&#39;&#233;tat s&#233;lectionn&#233;');
define('_AM_SF_ANSWERS', 'R&#233;ponses');
define('_AM_SF_ALLFAQS', 'Q&#38;R du Module');
define('_AM_SF_ALLFAQSMSG', 'S&#233;lectionnez un statut pour visualiser toutes les questions et/ou les r&#233;ponses disponibles avec ce statut.');

define("_AM_SF_UPDATE", "Mise &#224; jour");

/**
 * @translation     Communauté Francophone des Utilisateurs de Xoops
 * @specification   _LANGCODE: fr
 * @specification   _CHARSET: UTF-8
 *
 * @version         $Id: admin.php 1304 2010-10-17 22:21:07Z kris_fr $
**/
?>