<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;


// Belgian holidays
$this->holidays = array(
	'2003-1-1'=>1,'2003-4-21'=>1,'2003-5-1'=>1,
	'2003-5-29'=>1,'2003-6-9'=>1,'2003-7-11'=>1,'2003-7-21'=>1, '2003-8-15'=>1,
	'2003-11-1'=>1,'2003-11-11'=>1,'2003-12-25'=>1,
	
	'2004-1-1'=>1,'2003-4-12'=>1,'2003-5-1'=>1,
	'2003-5-20'=>1,'2003-5-31'=>1,'2003-7-11'=>1, '2003-7-21'=>1, '2003-8-15'=>1,
	'2003-11-1'=>1,'2003-11-11'=>1,'2003-12-25'=>1,
	

	); 

// Can't use tags (for options)
$this->date_short_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can use tags
$this->date_long_names = array(
	'0','1','2','3','4','5','6','7','8','9',
	'10','11','12','13','14','15','16','17','18','19',
	'20','21','22','23','24','25','26','27','28','29',
	'30','31'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Week 0','Week 1','Week 2','Week 3','Week 4','Week 5','Week 6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Zo','Ma','Di','Wo','Do','Vr','Za','Zo') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Zo','Ma','Di','Wo','Do','Vr','Za','Zo') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Zondag','Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag','Zondag') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Jan','Feb','Maa','Apr','Mei','Jun','Jul','Aug','Sep','Okt','Nov','Dec') ; 

// Can use tags
$this->month_middle_names = array('0','Jan','Feb','Maa','Apr','Mei','Jun','Jul','Aug','Sep','Okt','Nov','Dec') ; 

// Can use tags
$this->month_long_names = array('0','Januari','Februari','Maart','April','Mei','Juni','Juli','Augustus','September','Oktober','November','December') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'So','MO'=>'Ma','TU'=>'Di','WE'=>'Wo','TH'=>'Do','FR'=>'Vr','SA'=>'Za') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1ste Zondag','1MO'=>'1ste Maandag','1TU'=>'1ste Dinsdag','1WE'=>'1ste Woensdag','1TH'=>'1ste Donderdag','1FR'=>'1ste Vrijdag','1SA'=>'1ste Zaterdag',
	'2SU'=>'2de Zondag','2MO'=>'2de Maandag','2TU'=>'2de Dinsdag','2WE'=>'2de Woensdag','2TH'=>'2de Donderdag','2FR'=>'2de Vrijdag','2SA'=>'2de Zaterdag',
	'3SU'=>'3de Zondag','3MO'=>'3de Maandag','3TU'=>'3de Dinsdag','3WE'=>'3de Woensdag','3TH'=>'3de Donderdag','3FR'=>'3de Vrijdag','3SA'=>'3de Zaterdag',
	'4SU'=>'4de Zondag','4MO'=>'4de Maandag','4TU'=>'4de Dinsdag','4WE'=>'4de Woensdag','4TH'=>'4de Donderdag','4FR'=>'4de Vrijdag','4SA'=>'4de Zaterdag',
	'-1SU'=>'Laatste zondag','-1MO'=>'Laatste maandag','-1TU'=>'Laatste dinsdag','-1WE'=>'Laatste woensdag','-1TH'=>'Laatste donderdag','-1FR'=>'Laatste vrijdag','-1SA'=>'Laatste zaterdag'
	) ;

?>
