<?php
/**
 * $Id: main.php,v 1.1 2007/02/10 18:55:29 dap997 Exp $
 * Module: Wordbook - a multicategory glossary
 * Version: v 1.00
 * Release Date: 8 May 2004
 * Author: hsalazar; PL by malcolm_x
 * Licence: GNU
 */
define("_AM_WB_NOCOLEXISTS","Sorry, there&#8217s no category defined as yet.<br />Please contact the site administrator and tell him about this.");
define("_MD_WB_ALL","Wszystkie");
define("_MD_WB_ALLCATS","Wszystkie kategorie");
define("_MD_WB_ALLOFTHEM","0 : Wszystkie z nich");
define("_MD_WB_ANDOR","Search scope");
define("_MD_WB_ANDORALL","Wszystkie s³owa (AND)");
define("_MD_WB_ANDORANY","Którekolwiek (OR)");
define("_MD_WB_ANDOREXACT","Dok³adnie pasuj±ce");
define("_MD_WB_ANONYMOUS","Anonimowy");
define("_MD_WB_ASKEDBY","Term asked by:");
define("_MD_WB_ASKFORDEF","Popro¶ o definicjê");
define("_MD_WB_BEGINWITHLETTER","wpisów, które zaczynaj± siê na t± literê.");
define("_MD_WB_BROWSECAT","Browse by category");
define("_MD_WB_BROWSELETTER","Szukaj wg alfabetu");
define("_MD_WB_CATEGORY","Search in category");
define("_MD_WB_CATS","Kategorie: ");
define("_MD_WB_COUNT","This entry has been seen individually %s times.");
define("_MD_WB_CREATE","Wprowad¼ wyra¿enie");
define("_MD_WB_DEFINITION","[*] Definicja");
define("_MD_WB_DEFINITIONREQ","Glossary definition request");
define("_MD_WB_DEFINITIONSUB","Glossary definition submission");
define("_MD_WB_DEFINS","Definicje");
define("_MD_WB_DEFS","Definicje: ");
define("_MD_WB_DELTERM","Delete this term");
define("_MD_WB_EDITTERM","Edytuj to wyra¿enie");
define("_MD_WB_EMAILLEFT","The user left this mail address: ");
define("_MD_WB_ENTRIES"," wpisy.");
define("_MD_WB_ENTRIESINCAT","entries in this glossary.");
define("_MD_WB_ENTRY","[*] Wpis");
define("_MD_WB_ENTRYCATEGORY","Kategoria: ");
define("_MD_WB_ENTRYCOUNT","This category has ");
define("_MD_WB_ENTRYDEFINITION","Definicja: ");
define("_MD_WB_ENTRYREFERENCE","¬ród³o: ");
define("_MD_WB_ENTRYRELATEDURL","Strona WWW na temat: ");
define("_MD_WB_ERRORSAVINGDB","ERROR: Database has NOT been Updated due to an Error!");
define("_MD_WB_GOODDAY","Dobrego dnia, ");
define("_MD_WB_GOODDAY2","Dobrego dnia, %s.");
define("_MD_WB_HOME","Strona g³ówna");
define("_MD_WB_INALLGLOSSARIES","wpisów w s³owniku.");
define("_MD_WB_INTENTRY","Zobacz ciekaw± definicjê %s");
define("_MD_WB_INTENTRYFOUND","Tutaj mo¿na znale¼æ interesuj±cy termin %s");
define("_MD_WB_INTROREQUEST","Didn't find in our Glossary the definition you were looking for? Submit us the term by filling this form. We will look for its definition and add it to the database.");
define("_MD_WB_LOOKON","Szukaj w");
define("_MD_WB_MAINHEAD","Witaj w %s");
define("_MD_WB_MAININTRO","In this area of the site you will find our catalogue of glossary entries, as well as the latest entry from each of our categories. Click on a category&#8217s name to see all the entries associated to that category, or on an entry&#8217s name to read directly the entry. Depending on privileges, you can rate each entry, select notification options or leave your comments.");
define("_MD_WB_MAINNOSELECTCAT","You did not select a valid category");
define("_MD_WB_MAINNOTOPICS","Nie ma wpisów w tej kategorii");
define("_MD_WB_MESSAGESENT","Message to %s sent.");
define("_MD_WB_NO","Nie");
define("_MD_WB_NOENTRIESINCAT","Nie ma jeszcze wpisów w tym s³owniku.");
define("_MD_WB_NORESULTS","There were no correspondences with the search term. Please use another word and try again.");
define("_MD_WB_NOSEARCHTERM","You have not declared a search term. Please do it now in the search form included in this page.");
define("_MD_WB_NOTERMSINLETTER","Nie ma wpisów na t± literê.");
define("_MD_WB_NOTIFY","Powiadom po wprowadzeniu?");
define("_MD_WB_NOTIFYONPUB","The user has asked to be notified when we do something about the definition.<br />");
define("_MD_WB_OTHER","Inne");
define("_MD_WB_POPULARENT","Popularne terminy");
define("_MD_WB_POSTED","Opublikowane");
define("_MD_WB_PRINTERFRIENDLY","Print this entry in a printer friendly format");
define("_MD_WB_PRINTTERM","Drukuj w przyjaznym formacie");
define("_MD_WB_RANDOMTERM","Losowe wyra¿enie");
define("_MD_WB_RECEIVED","The entry you sent has been received. We&#8217ll look at it as soon as possible.");
define("_MD_WB_RECEIVEDANDAPPROVED","The entry you sent has been received. Since the auto-approve option is on, we&#8217ll publish it at once.");
define("_MD_WB_RECENTENT","Ostatnie wpisy");
define("_MD_WB_REFERENCE","Reference<span style='font-size: xx-small; font-weight: normal; display: block;'>(You may optionally include here the source of your definition.)</span>");
define("_MD_WB_REQRCVD","Your request has been received. We'll look at it as soon as possible.");
define("_MD_WB_REQSEND","Requisition sent");
define("_MD_WB_REQTERM","[*] Wyra¿enie do zdefiniowania");
define("_MD_WB_REQUESTDEF","Popro¶ o definicjê");
define("_MD_WB_REQUESTFORM","Popro¶ o definicjê");
define("_MD_WB_REQUESTSENT","Your request has been forwarded to the webmaster of %s.");
define("_MD_WB_RETURN","Wróæ");
define("_MD_WB_RETURN2INDEX","Wróæ");
define("_MD_WB_SEARCH","Szukaj!");
define("_MD_WB_SEARCHENTRY","Szukaj wpisu");
define("_MD_WB_SEARCHHEAD","Wyniki wyszukiwania");
define("_MD_WB_SECTIONNAME","S³ownik");
define("_MD_WB_SEEMORE","Wiêcej definicji...");
define("_MD_WB_SENDSTORY","Wy¶lij do przyjaciela");
define("_MD_WB_SENDTOFRIEND","Wy¶lij do przyjaciela");
define("_MD_WB_SENT","Opublikowane: ");
define("_MD_WB_SENTCONFIRMMAIL","Your comments have been sent to <b>%s</b> as a confirmation email.");
define("_MD_WB_STILLNOTHINGHERE","<h4 style='margin: 0;'>Glossaries empty</h4>Sorry: We don't have entries in our glossaries yet. You can help us by requesting some entries whose meaning you wish to know. If you're a registered user, you can also help by submitting some terms whose definition you know.");
define("_MD_WB_SUB_SMNAME","Fill this form to send your entry");
define("_MD_WB_SUB_SNEWNAME","Dodaj wpis do %s");
define("_MD_WB_SUB_SNEWNAMEDESC","please fill the following form to submit your new entry to our site. As you&#8217re well aware, it&#8217ll have to be validated by an administrator before it gets published. However, if the administrator has activated the auto-approve setting, your entry will be instantly published.");
define("_MD_WB_SUBMIT","Potwierd¼ pro¶bê");
define("_MD_WB_SUBMITART","Dodaj wyra¿enie");
define("_MD_WB_SUBMITENTRY","Dodaj wyra¿enie");
define("_MD_WB_SUBMITTED","Dodane przez %s, dnia %s.");
define("_MD_WB_SUBMITTER","Autor: ");
define("_MD_WB_TERM","Szukane wyra¿enia");
define("_MD_WB_TERMS","Wyra¿enia");
define("_MD_WB_TERMSDEFS","Wyra¿enia i definicje");
define("_MD_WB_THANKS1","Thank you for your participation!<br />");
define("_MD_WB_THANKS2","Thank you for asking from us a definition!");
define("_MD_WB_THANKYOU","Thank you for taking the time to ask from us a definition that will enrich the glossaries of %s.");
define("_MD_WB_THEREWERE","There were %s entries matching the search term: <b>%s</b>.");
define("_MD_WB_TIMESREAD","Przeczytane razy");
define("_MD_WB_UNKNOWNERROR","ERROR.  Returning you to where you where!");
define("_MD_WB_URL","URL<span style='font-size: xx-small; font-weight: normal; display: block;'>(Please enter a valid URL with or without the HTTP prefix.)</span>");
define("_MD_WB_USERMAIL","E-mail");
define("_MD_WB_USERNAME","U¿ytkownik");
define("_MD_WB_WEBMASTER","Webmaster");
define("_MD_WB_WEHAVE","W tej chwili mamy");
define("_MD_WB_WHOASKED","%s asked us to find the definition for: ");
define("_MD_WB_WHOSUBMITTED","%s has submitted the definition for this term: ");
define("_MD_WB_YES","Yes");

define("_MD_WB_OPTIONS","Options");
define("_MD_WB_DOHTML","Allow HTML?");
define("_MD_WB_DOSMILEY","Allow smilies?");
define("_MD_WB_DOXCODE","Allow XOOPS Codes?");
define("_MD_WB_BREAKS","Allow linebreaks?");
define("_MD_WB_SUBANDREQ","Submitted and requested terms");
define("_MD_WB_SUB","Submitted terms: ");
define("_MD_WB_REQ","Requested terms: ");
define("_MD_WB_NOSUB","Currently there are no submitted terms.");
define("_MD_WB_NOREQ","Currently there are no requested terms.");
define("_MD_WB_WRITEHERE","Please write here the definition.");
define("_MD_WB_GUEST","Guest");
define("_MD_WB_NOCATSINSYSTEM","No categories in system");
define("_MD_WB_REQUESTSUGGEST","(Click the next words to suggest a definition for the term)");
?>
