/**
* Translation of TinyMCE for Persian users
*
* @copyright	      http://www.impresscms.org/ The ImpressCMS Project 
* @license		http://www.gnu.org/licenses/old-licenses/gpl-2.0.html GNU General Public License (GPL)
* @package	      Translations
* @since		 3.0.6.2
* @author		Sina Asghari <pesian_stranger@users.sourceforge.net>
* @version		$Id$
*/
tinyMCE.addI18n('fa.style_dlg',{
title:"ویرایش ترکیب‌بندی CSS",
styleinfo_desc:"ویرایش ترکیب‌بندی پرونده‌های CSS",
apply:"بکاربردن",
text_tab:"متن",
background_tab:"پس‌زمینه",
block_tab:"بلوک",
box_tab:"جعبه",
border_tab:"حاشیه",
list_tab:"لیست",
positioning_tab:"موقعیت",
text_props:"متن",
text_font:"قلم",
text_size:"اندازه",
text_weight:"ترتیب",
text_style:"ترکیب‌بندی",
text_variant:"متغیر",
text_lineheight:"بلندی خط",
text_case:"کوچکی بزرگی حروف",
text_color:"رنگ",
text_decoration:"تزیین",
text_overline:"بالا خط",
text_underline:"زیر خط",
text_striketrough:"وسط خط",
text_blink:"چشمک زن",
text_none:"هیچ کدام",
background_color:"رنگ پس‌زمینه",
background_image:"تصویر پس‌زمینه",
background_repeat:"تکرار",
background_attachment:"ضمیمه",
background_hpos:"موقعیت افقی",
background_vpos:"موقعیت عمودی",
block_wordspacing:"فاصله کلمه",
block_letterspacing:"فاصله حرف",
block_vertical_alignment:"هم‌ترازی عمودی",
block_text_align:"تراز متن",
block_text_indent:"فرورفتگی متن",
block_whitespace:"فاصله سفید",
block_display:"نمایش",
box_width:"پهنا",
box_height:"ارتفاع",
box_float:"شناور",
box_clear:"صاف",
padding:"لایی‌گذاری",
same:"یکسان برای همه",
top:"بالا",
right:"راست",
bottom:"پایین",
left:"چپ",
margin:"حاشیه",
style:"ترکیب‌بندی",
width:"پهنا",
height:"ارتفاع",
color:"رنگ",
list_type:"نوع",
bullet_image:"تصویر گلوله",
position:"موقعیت",
positioning_type:"نوع",
visibility:"پدیداری",
zindex:"شاخص Z",
overflow:"سرریز",
placement:"جای‌گذاری",
clip:"کلیپ",
});