<?php

// Hour names for 24hour system
$this->hour_names_24 = array(
	'0','1','2','3','4','5',
	'6','7','8','9','10','11',
	'12','13','14','15','16','17',
	'18','19','20','21','22','23',
	'next 0','next 1','next 2','next 3','next 4','next 5',
	'next 6','next 7','next 8','next 9','next 10','next 11'
	) ;

// Hour names for 12hour system
$this->hour_names_12 = array(
	'AM 0','AM 1','AM 2','AM 3','AM 4','AM 5',
	'AM 6','AM 7','AM 8','AM 9','AM 10','AM 11',
	'PM 0','PM 1','PM 2','PM 3','PM 4','PM 5',
	'PM 6','PM 7','PM 8','PM 9','PM 10','PM 11',
	'next AM 0','next AM 1','next AM 2','next AM 3','next AM 4','next AM 5',
	'next AM 6','next AM 7','next AM 8','next AM 9','next AM 10','next AM 11'
	) ;

// Can't use tags (for options)
$this->date_short_names = array(
	'0th','1st','2nd','3rd','4th','5th','6th','7th','8th','9th',
	'10th','11th','12th','13th','14th','15th','16th','17th','18th','19th',
	'20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th',
	'30th','31st'
	) ;

// Can use tags
$this->date_long_names = array(
	'0th','1st','2nd','3rd','4th','5th','6th','7th','8th','9th',
	'10th','11th','12th','13th','14th','15th','16th','17th','18th','19th',
	'20th','21st','22nd','23rd','24th','25th','26th','27th','28th','29th',
	'30th','31st'
	) ;

// Can't use tags (for options)
$this->week_numbers = array('Week0','Week1','Week2','Week3','Week4','Week5','Week6') ;

// Can't use tags (for options & minicalendar)
$this->week_short_names = array('Ndz','Pon','Wt','¦r','Czw','Pt','So','Ndz') ;

// Can use tags (for Monthly & Weekly View)
$this->week_middle_names = array('Ndz','Pon','Wt','¦r','Czw','Pt','So','Ndz') ;

// Can use tags (for Daily View)
$this->week_long_names = array('Niedziela','Poniedzia³ek','Wtorek','¦roda','Czwartek','Pi±tek','Sobota','Niedziela') ;

// Can't use tags (for options)
$this->month_short_names = array('0','Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Pa¼','Lis','Gru') ;

// Can use tags
$this->month_middle_names = array('0','Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Pa¼','Lis','Gru') ;

// Can use tags
$this->month_long_names = array('0','Styczeñ','Luty','Marzec','Kwiecieñ','Maj','Czerwiec','Lipiec','Sierpieñ','Wrzesieñ','Pa¼dziernik','Listopad','Grudzieñ') ;

// Don't change keys at all, but change values only
$this->byday2langday_w = array('SU'=>'Sun','MO'=>'Mon','TU'=>'Tue','WE'=>'Wed','TH'=>'Thu','FR'=>'Fri','SA'=>'Sat') ;

// Don't change keys at all, but change values only
$this->byday2langday_m = array(
	'1SU'=>'1st Sunday','1MO'=>'1st Monday','1TU'=>'1st Tuesday','1WE'=>'1st Wednesday','1TH'=>'1st Thursday','1FR'=>'1st Friday','1SA'=>'1st Saturday',
	'2SU'=>'2nd Sunday','2MO'=>'2nd Monday','2TU'=>'2nd Tuesday','2WE'=>'2nd Wednesday','2TH'=>'2nd Thursday','2FR'=>'2nd Friday','2SA'=>'2nd Saturday',
	'3SU'=>'3rd Sunday','3MO'=>'3rd Monday','3TU'=>'3rd Tuesday','3WE'=>'3rd Wednesday','3TH'=>'3rd Thursday','3FR'=>'3rd Friday','3SA'=>'3rd Saturday',
	'4SU'=>'4th Sunday','4MO'=>'4th Monday','4TU'=>'4th Tuesday','4WE'=>'4th Wednesday','4TH'=>'4th Thursday','4FR'=>'4th Friday','4SA'=>'4th Saturday',
	'-1SU'=>'Last Sunday','-1MO'=>'Last Monday','-1TU'=>'Last Tuesday','-1WE'=>'Last Wednesday','-1TH'=>'Last Thursday','-1FR'=>'Last Friday','-1SA'=>'Last Saturday'
	) ;



?>