<?php
// $Id: blacksadmin.php 2008-07-29 11:32+09:00 2 8 6 $
//%%%%%%	Admin Module Name  Blocks 	%%%%%
define("_AM_DBUPDATED",_MD_AM_DBUPDATED);

//%%%%%%	blocks.php 	%%%%%
define("_AM_BADMIN","�֥�å�����");
define("_AM_ADDBLOCK","�����֥�å�����");
define("_AM_LISTBLOCK","���ƤΥ֥�å���ɽ��");
define("_AM_SIDE","ɽ��������");
define("_AM_BLKDESC","�֥�å�������");
define("_AM_TITLE","�����ȥ�");
define("_AM_WEIGHT","�¤ӽ�");
define("_AM_ACTION","���");
define("_AM_BLKTYPE","�֥�å��Υ�����");
define("_AM_LEFT","��¦");
define("_AM_RIGHT","��¦");
define("_AM_CENTER","���");
define("_AM_VISIBLE","ɽ�� / ��ɽ��");
define("_AM_POSCONTT","�ɲå���ƥ�Ĥ������������");
define("_AM_ABOVEORG","���Υ���ƥ�Ĥξ�");
define("_AM_AFTERORG","���Υ���ƥ�Ĥβ�");
define("_AM_EDIT","�Խ�");
define("_AM_DELETE","���");
define("_AM_SBLEFT","�����ɥ֥�å� - ��");
define("_AM_SBRIGHT","�����ɥ֥�å� - ��");
define("_AM_CBLEFT","����֥�å� - ��");
define("_AM_CBRIGHT","����֥�å� - ��");
define("_AM_CBCENTER","����֥�å� - ���");
define("_AM_CBBOTTOMLEFT","����֥�å� - ����");
define("_AM_CBBOTTOMRIGHT","����֥�å� - ����");
define("_AM_CBBOTTOM","����֥�å� - ��");
define("_AM_CONTENT","����ƥ��");
define("_AM_OPTIONS","���ץ����");
define("_AM_CTYPE","����ƥ�ĤΥ�����");
define("_AM_HTML","HTML����");
define("_AM_PHP","PHP������ץ�");
define("_AM_AFWSMILE","��ư�ե����ޥåȡʴ饢������ͭ����");
define("_AM_AFNOSMILE","��ư�ե����ޥåȡʴ饢������̵����");
define("_AM_SUBMIT","����");
define("_AM_CUSTOMHTML","���������HTML��");
define("_AM_CUSTOMPHP","���������PHP��");
define("_AM_CUSTOMSMILE","��������ʴ饢������̵����");
define("_AM_CUSTOMNOSMILE","��������ʴ饢������̵����");
define("_AM_DISPRIGHT","���֥�å��Τ�ɽ��");
define("_AM_SAVECHANGES","�ѹ�����¸");
define("_AM_EDITBLOCK","�֥�å����Խ�");
define("_AM_SYSTEMCANT","�����ƥ�֥�å��Ϻ���Ǥ��ޤ���");
define("_AM_MODULECANT","���Υ֥�å���ľ�ܺ�����뤳�ȤϤǤ��ޤ�����ˤ��Υ֥�å��Υ⥸�塼����󥢥��ƥ��֤ˤ��Ƥ�������");
define("_AM_RUSUREDEL","<b>%s</b>�֥�å��������˺�����Ƥ⤤���Ǥ�����");
define("_AM_NAME","̾��");
define("_AM_USEFULTAGS","���Ѳ�ǽ�ʥ���");
define("_AM_BLOCKTAG1","%s �� %s ��ɽ�����ޤ�");
define('_AM_SVISIBLEIN','ɽ��������̡� %s ');//Show blocks visible in %s');
define('_AM_TOPPAGE','�ȥåץڡ���');
define('_AM_VISIBLEIN','ɽ���������');
define('_AM_ALLPAGES','���٤ƤΥڡ���');
define('_AM_TOPONLY','�ȥåץڡ����Τ�');
define('_AM_ADVANCED','���٤�����');
define('_AM_BCACHETIME','����å���μ�̿');
define('_AM_BALIAS','���ꥢ��̾');
define('_AM_CLONE','ʣ��');  // clone a block
define('_AM_CLONEBLK','ʣ��'); // cloned block
define('_AM_CLONEBLOCK','ʣ���֥�å��κ���');
define('_AM_NOTSELNG',"'%s' �����򤵤�Ƥ��ޤ���!"); // error message
define('_AM_EDITTPL','�ƥ�ץ졼�Ȥ��Խ�');
define('_AM_MODULE','�⥸�塼��');
define('_AM_GROUP','���롼��');
define('_AM_UNASSIGNED','̤�������');

define("_AM_CUSTOM","Custom Block");
define('_AM_GENERATOR','Blocks generated by %s');
define('_AM_TYPES','All types');
?>